// =======================================================================
// MARKETMIND — SEED  (GENERATED by tools/gen_seed.py — DO NOT HAND-EDIT)
// Source of truth: data/companies.json + edges.json + events.json + macro.json
// Idempotent (MERGE). Safe to re-run. Run in Neo4j Browser or cypher-shell.
//
// 104 companies · 257 cascade edges · 27 events
// macro: 5 commodities · 7 themes · 2 conditions · 201 exposure edges (SEED-ONLY)
//
// Cascade walks ONLY SUPPLIES_TO|PARTNERS_WITH|OWNS|COMPETES_WITH. Country/Sector/Commodity/
// Theme/Condition + exposure edges are SEED-ONLY context — never traversed company->company.
// =======================================================================

// ---------- Constraints ----------
CREATE CONSTRAINT company_ticker IF NOT EXISTS FOR (c:Company)      REQUIRE c.ticker IS UNIQUE;
CREATE CONSTRAINT news_id        IF NOT EXISTS FOR (n:NewsEvent)    REQUIRE n.id     IS UNIQUE;
CREATE CONSTRAINT impact_id      IF NOT EXISTS FOR (i:ImpactRecord) REQUIRE i.id     IS UNIQUE;
CREATE CONSTRAINT country_code   IF NOT EXISTS FOR (k:Country)      REQUIRE k.code   IS UNIQUE;
CREATE CONSTRAINT sector_name    IF NOT EXISTS FOR (s:Sector)       REQUIRE s.name   IS UNIQUE;
CREATE CONSTRAINT commodity_id   IF NOT EXISTS FOR (m:Commodity)    REQUIRE m.id     IS UNIQUE;
CREATE CONSTRAINT theme_id       IF NOT EXISTS FOR (h:Theme)        REQUIRE h.id     IS UNIQUE;
CREATE CONSTRAINT condition_id   IF NOT EXISTS FOR (d:Condition)    REQUIRE d.id     IS UNIQUE;

// ---------- Companies ----------
// tr = tradable, p = yfinance priceTicker (null = not directly tradable), bm = local benchmark, lf = first trade date, lat/lng = HQ coords (geo map)
UNWIND [
  {t:'MSFT', n:'Microsoft', s:'cloud', co:'US', tr:true, p:'MSFT', bm:'SPY', lf:null, lat:47.64, lng:-122.13},
  {t:'NVDA', n:'NVIDIA', s:'semis', co:'US', tr:true, p:'NVDA', bm:'SPY', lf:'1999-01-22', lat:37.37, lng:-121.97},
  {t:'TSMC', n:'TSMC', s:'semis', co:'TW', tr:true, p:'TSM', bm:'SPY', lf:'1997-10-08', lat:24.77, lng:121.01},
  {t:'ASML', n:'ASML', s:'semis', co:'NL', tr:true, p:'ASML', bm:'SPY', lf:'1995-03-14', lat:51.42, lng:5.4},
  {t:'AMD', n:'AMD', s:'semis', co:'US', tr:true, p:'AMD', bm:'SPY', lf:'1972-09-27', lat:37.37, lng:-121.97},
  {t:'INTC', n:'Intel', s:'semis', co:'US', tr:true, p:'INTC', bm:'SPY', lf:'1971-10-13', lat:37.39, lng:-121.96},
  {t:'MU', n:'Micron', s:'semis', co:'US', tr:true, p:'MU', bm:'SPY', lf:'1984-06-01', lat:43.62, lng:-116.21},
  {t:'AVGO', n:'Broadcom', s:'semis', co:'US', tr:true, p:'AVGO', bm:'SPY', lf:'2009-08-06', lat:37.42, lng:-122.14},
  {t:'QCOM', n:'Qualcomm', s:'semis', co:'US', tr:true, p:'QCOM', bm:'SPY', lf:'1991-12-13', lat:32.9, lng:-117.2},
  {t:'ARM', n:'Arm Holdings', s:'semis', co:'GB', tr:true, p:'ARM', bm:'SPY', lf:null, lat:52.19, lng:0.13},
  {t:'TXN', n:'Texas Instruments', s:'semis', co:'US', tr:true, p:'TXN', bm:'SPY', lf:null, lat:32.75, lng:-96.75},
  {t:'MRVL', n:'Marvell Technology', s:'semis', co:'US', tr:true, p:'MRVL', bm:'SPY', lf:null, lat:37.39, lng:-121.97},
  {t:'LRCX', n:'Lam Research', s:'semis', co:'US', tr:true, p:'LRCX', bm:'SPY', lf:null, lat:37.55, lng:-121.99},
  {t:'AMAT', n:'Applied Materials', s:'semis', co:'US', tr:true, p:'AMAT', bm:'SPY', lf:null, lat:37.39, lng:-121.98},
  {t:'SMSN', n:'Samsung Electronics', s:'semis', co:'KR', tr:true, p:'005930.KS', bm:'^KS11', lf:'1975-06-11', lat:37.26, lng:127.03},
  {t:'SKH', n:'SK hynix', s:'semis', co:'KR', tr:true, p:'000660.KS', bm:'^KS11', lf:'1996-12-26', lat:37.45, lng:127.55},
  {t:'AWS', n:'Amazon Web Services', s:'cloud', co:'US', tr:false, p:'AMZN', bm:null, lf:null, lat:47.62, lng:-122.34},
  {t:'GCP', n:'Google Cloud', s:'cloud', co:'US', tr:false, p:'GOOGL', bm:null, lf:null, lat:37.42, lng:-122.08},
  {t:'ORCL', n:'Oracle', s:'cloud', co:'US', tr:true, p:'ORCL', bm:'SPY', lf:null, lat:30.27, lng:-97.74},
  {t:'IBM', n:'IBM', s:'cloud', co:'US', tr:true, p:'IBM', bm:'SPY', lf:null, lat:41.11, lng:-73.72},
  {t:'OPENAI', n:'OpenAI', s:'ai', co:'US', tr:false, p:null, bm:null, lf:null, lat:37.77, lng:-122.41},
  {t:'XAI', n:'xAI', s:'ai', co:'US', tr:false, p:null, bm:null, lf:null, lat:37.44, lng:-122.14},
  {t:'ANTHROPIC', n:'Anthropic', s:'ai', co:'US', tr:false, p:null, bm:null, lf:null, lat:37.77, lng:-122.41},
  {t:'PPLX', n:'Perplexity', s:'ai', co:'US', tr:false, p:null, bm:null, lf:null, lat:37.77, lng:-122.41},
  {t:'COHERE', n:'Cohere', s:'ai', co:'CA', tr:false, p:null, bm:null, lf:null, lat:43.65, lng:-79.38},
  {t:'MISTRAL', n:'Mistral AI', s:'ai', co:'FR', tr:false, p:null, bm:null, lf:null, lat:48.85, lng:2.35},
  {t:'AMZN', n:'Amazon', s:'internet', co:'US', tr:true, p:'AMZN', bm:'SPY', lf:null, lat:47.62, lng:-122.34},
  {t:'GOOGL', n:'Alphabet', s:'internet', co:'US', tr:true, p:'GOOGL', bm:'SPY', lf:null, lat:37.42, lng:-122.08},
  {t:'META', n:'Meta Platforms', s:'internet', co:'US', tr:true, p:'META', bm:'SPY', lf:null, lat:37.48, lng:-122.15},
  {t:'NFLX', n:'Netflix', s:'internet', co:'US', tr:true, p:'NFLX', bm:'SPY', lf:null, lat:37.23, lng:-121.96},
  {t:'BABA', n:'Alibaba', s:'internet', co:'CN', tr:true, p:'BABA', bm:'SPY', lf:'2014-09-19', lat:30.27, lng:120.16},
  {t:'GITHUB', n:'GitHub', s:'internet', co:'US', tr:false, p:'MSFT', bm:null, lf:null, lat:37.78, lng:-122.4},
  {t:'AAPL', n:'Apple', s:'hardware', co:'US', tr:true, p:'AAPL', bm:'SPY', lf:'1980-12-12', lat:37.33, lng:-122.03},
  {t:'DELL', n:'Dell Technologies', s:'hardware', co:'US', tr:true, p:'DELL', bm:'SPY', lf:null, lat:30.51, lng:-97.69},
  {t:'SMCI', n:'Super Micro Computer', s:'hardware', co:'US', tr:true, p:'SMCI', bm:'SPY', lf:null, lat:37.34, lng:-121.89},
  {t:'ANET', n:'Arista Networks', s:'hardware', co:'US', tr:true, p:'ANET', bm:'SPY', lf:null, lat:37.37, lng:-121.97},
  {t:'CSCO', n:'Cisco Systems', s:'hardware', co:'US', tr:true, p:'CSCO', bm:'SPY', lf:null, lat:37.41, lng:-121.95},
  {t:'FOXCONN', n:'Foxconn (Hon Hai)', s:'hardware', co:'TW', tr:true, p:'2317.TW', bm:'^TWII', lf:null, lat:25.01, lng:121.37},
  {t:'WDC', n:'Western Digital', s:'hardware', co:'US', tr:true, p:'WDC', bm:'SPY', lf:null, lat:37.33, lng:-121.9},
  {t:'STX', n:'Seagate', s:'hardware', co:'US', tr:true, p:'STX', bm:'SPY', lf:null, lat:37.49, lng:-121.94},
  {t:'TSLA', n:'Tesla', s:'automotive', co:'US', tr:true, p:'TSLA', bm:'SPY', lf:'2010-06-29', lat:30.22, lng:-97.62},
  {t:'GM', n:'General Motors', s:'automotive', co:'US', tr:true, p:'GM', bm:'SPY', lf:'2010-11-18', lat:42.33, lng:-83.04},
  {t:'BYD', n:'BYD', s:'automotive', co:'CN', tr:true, p:'1211.HK', bm:'^HSI', lf:'2002-07-31', lat:22.65, lng:114.02},
  {t:'CATL', n:'CATL', s:'automotive', co:'CN', tr:true, p:'300750.SZ', bm:'000300.SS', lf:null, lat:26.67, lng:119.55},
  {t:'PANA', n:'Panasonic', s:'automotive', co:'JP', tr:true, p:'6752.T', bm:'^N225', lf:null, lat:34.74, lng:135.58},
  {t:'V', n:'Visa', s:'finance', co:'US', tr:true, p:'V', bm:'SPY', lf:'2008-03-19', lat:37.55, lng:-122.27},
  {t:'MA', n:'Mastercard', s:'finance', co:'US', tr:true, p:'MA', bm:'SPY', lf:'2006-05-25', lat:41.04, lng:-73.71},
  {t:'PYPL', n:'PayPal', s:'finance', co:'US', tr:true, p:'PYPL', bm:'SPY', lf:null, lat:37.33, lng:-121.89},
  {t:'JPM', n:'JPMorgan Chase', s:'finance', co:'US', tr:true, p:'JPM', bm:'SPY', lf:'1980-03-17', lat:40.75, lng:-73.97},
  {t:'GS', n:'Goldman Sachs', s:'finance', co:'US', tr:true, p:'GS', bm:'SPY', lf:'1999-05-04', lat:40.71, lng:-74.01},
  {t:'4063.T', n:'Shin-Etsu Chemical', s:'semis', co:'JP', tr:true, p:'4063.T', bm:'^N225', lf:null, lat:35.68, lng:139.74},
  {t:'3436.T', n:'SUMCO Corporation', s:'semis', co:'JP', tr:true, p:'3436.T', bm:'^N225', lf:null, lat:35.66, lng:139.73},
  {t:'ENTG', n:'Entegris', s:'semis', co:'US', tr:true, p:'ENTG', bm:'SPY', lf:null, lat:42.55, lng:-71.27},
  {t:'LIN', n:'Linde plc', s:'semis', co:'GB', tr:true, p:'LIN', bm:'SPY', lf:null, lat:51.32, lng:-0.56},
  {t:'AI.PA', n:'Air Liquide', s:'semis', co:'FR', tr:true, p:'AI.PA', bm:'^STOXX50E', lf:null, lat:48.87, lng:2.31},
  {t:'8035.T', n:'Tokyo Electron', s:'semis', co:'JP', tr:true, p:'8035.T', bm:'^N225', lf:null, lat:35.68, lng:139.74},
  {t:'KLAC', n:'KLA Corporation', s:'semis', co:'US', tr:true, p:'KLAC', bm:'SPY', lf:null, lat:37.43, lng:-121.9},
  {t:'6857.T', n:'Advantest', s:'semis', co:'JP', tr:true, p:'6857.T', bm:'^N225', lf:null, lat:35.69, lng:139.69},
  {t:'6920.T', n:'Lasertec', s:'semis', co:'JP', tr:true, p:'6920.T', bm:'^N225', lf:null, lat:35.45, lng:139.64},
  {t:'ASM.AS', n:'ASM International', s:'semis', co:'NL', tr:true, p:'ASM.AS', bm:'^STOXX50E', lf:null, lat:52.37, lng:5.22},
  {t:'SNPS', n:'Synopsys', s:'semis', co:'US', tr:true, p:'SNPS', bm:'SPY', lf:null, lat:37.39, lng:-122.02},
  {t:'CDNS', n:'Cadence Design Systems', s:'semis', co:'US', tr:true, p:'CDNS', bm:'SPY', lf:null, lat:37.3, lng:-121.95},
  {t:'SMIC', n:'Semiconductor Manufacturing International Corp', s:'semis', co:'CN', tr:true, p:'0981.HK', bm:'^HSI', lf:'2004-03-18', lat:31.23, lng:121.47},
  {t:'HUAHONG', n:'Hua Hong Semiconductor Limited', s:'semis', co:'CN', tr:true, p:'1347.HK', bm:'^HSI', lf:null, lat:31.23, lng:121.47},
  {t:'TENCENT', n:'Tencent Holdings Limited', s:'internet', co:'CN', tr:true, p:'0700.HK', bm:'^HSI', lf:'2004-06-16', lat:22.54, lng:114.06},
  {t:'BIDU', n:'Baidu, Inc.', s:'ai', co:'CN', tr:true, p:'BIDU', bm:'SPY', lf:'2005-08-05', lat:39.98, lng:116.3},
  {t:'XIAOMI', n:'Xiaomi Corporation', s:'hardware', co:'CN', tr:true, p:'1810.HK', bm:'^HSI', lf:'2018-07-09', lat:40.04, lng:116.28},
  {t:'JD', n:'JD.com, Inc.', s:'internet', co:'CN', tr:true, p:'JD', bm:'SPY', lf:null, lat:39.9, lng:116.4},
  {t:'NAVER', n:'NAVER Corporation', s:'internet', co:'KR', tr:true, p:'035420.KS', bm:'^KS11', lf:null, lat:37.4, lng:127.11},
  {t:'KIOXIA', n:'Kioxia Holdings Corporation', s:'semis', co:'JP', tr:true, p:'285A.T', bm:'^N225', lf:'2024-12-18', lat:35.68, lng:139.76},
  {t:'IFX.DE', n:'Infineon Technologies AG', s:'semis', co:'DE', tr:true, p:'IFX.DE', bm:'^STOXX50E', lf:'2000-03-13', lat:48.08, lng:11.64},
  {t:'STM', n:'STMicroelectronics N.V.', s:'semis', co:'CH', tr:true, p:'STM', bm:'SPY', lf:'1994-12-08', lat:46.18, lng:6.1},
  {t:'NXPI', n:'NXP Semiconductors N.V.', s:'semis', co:'NL', tr:true, p:'NXPI', bm:'SPY', lf:null, lat:51.41, lng:5.46},
  {t:'SAP', n:'SAP SE', s:'cloud', co:'DE', tr:true, p:'SAP', bm:'SPY', lf:null, lat:49.31, lng:8.64},
  {t:'SIE.DE', n:'Siemens AG', s:'hardware', co:'DE', tr:true, p:'SIE.DE', bm:'^STOXX50E', lf:null, lat:48.14, lng:11.58},
  {t:'SU.PA', n:'Schneider Electric S.E.', s:'energy', co:'FR', tr:true, p:'SU.PA', bm:'^STOXX50E', lf:null, lat:48.88, lng:2.18},
  {t:'NOK', n:'Nokia Oyj', s:'hardware', co:'FI', tr:true, p:'NOK', bm:'SPY', lf:null, lat:60.21, lng:24.66},
  {t:'ERIC', n:'Telefonaktiebolaget LM Ericsson', s:'hardware', co:'SE', tr:true, p:'ERIC', bm:'SPY', lf:null, lat:59.4, lng:17.95},
  {t:'VST', n:'Vistra', s:'energy', co:'US', tr:true, p:'VST', bm:'SPY', lf:'2016-10-03', lat:32.86, lng:-96.94},
  {t:'CEG', n:'Constellation Energy', s:'energy', co:'US', tr:true, p:'CEG', bm:'SPY', lf:'2022-01-19', lat:39.29, lng:-76.61},
  {t:'NRG', n:'NRG Energy', s:'energy', co:'US', tr:true, p:'NRG', bm:'SPY', lf:null, lat:29.76, lng:-95.37},
  {t:'GEV', n:'GE Vernova', s:'energy', co:'US', tr:true, p:'GEV', bm:'SPY', lf:'2024-04-02', lat:42.37, lng:-71.1},
  {t:'ETN', n:'Eaton', s:'energy', co:'US', tr:true, p:'ETN', bm:'SPY', lf:null, lat:41.46, lng:-81.5},
  {t:'VRT', n:'Vertiv Holdings', s:'energy', co:'US', tr:true, p:'VRT', bm:'SPY', lf:null, lat:40.13, lng:-82.93},
  {t:'PWR', n:'Quanta Services', s:'energy', co:'US', tr:true, p:'PWR', bm:'SPY', lf:null, lat:29.76, lng:-95.37},
  {t:'F', n:'Ford Motor', s:'automotive', co:'US', tr:true, p:'F', bm:'SPY', lf:null, lat:42.32, lng:-83.21},
  {t:'RIVN', n:'Rivian Automotive', s:'automotive', co:'US', tr:true, p:'RIVN', bm:'SPY', lf:null, lat:33.68, lng:-117.77},
  {t:'TM', n:'Toyota Motor', s:'automotive', co:'JP', tr:true, p:'TM', bm:'SPY', lf:'1999-09-16', lat:35.08, lng:137.16},
  {t:'VOW3', n:'Volkswagen', s:'automotive', co:'DE', tr:true, p:'VOW3.DE', bm:'^STOXX50E', lf:null, lat:51.1, lng:10.4},
  {t:'NIO', n:'NIO', s:'automotive', co:'CN', tr:true, p:'NIO', bm:'SPY', lf:'2018-09-12', lat:31.23, lng:121.47},
  {t:'LI', n:'Li Auto', s:'automotive', co:'CN', tr:true, p:'LI', bm:'SPY', lf:null, lat:40.04, lng:116.4},
  {t:'LGES', n:'LG Energy Solution', s:'automotive', co:'KR', tr:true, p:'373220.KS', bm:'^KS11', lf:null, lat:37.57, lng:126.98},
  {t:'ALB', n:'Albemarle', s:'energy', co:'US', tr:true, p:'ALB', bm:'SPY', lf:null, lat:35.23, lng:-80.84},
  {t:'RXRX', n:'Recursion Pharmaceuticals', s:'healthcare', co:'US', tr:true, p:'RXRX', bm:'SPY', lf:null, lat:40.76, lng:-111.89},
  {t:'SDGR', n:'Schrodinger', s:'healthcare', co:'US', tr:true, p:'SDGR', bm:'SPY', lf:null, lat:40.75, lng:-73.99},
  {t:'ILMN', n:'Illumina', s:'healthcare', co:'US', tr:true, p:'ILMN', bm:'SPY', lf:null, lat:32.87, lng:-117.21},
  {t:'TEM', n:'Tempus AI', s:'healthcare', co:'US', tr:true, p:'TEM', bm:'SPY', lf:'2024-06-14', lat:41.88, lng:-87.63},
  {t:'SNDK', n:'SanDisk', s:'semis', co:'US', tr:true, p:'SNDK', bm:'SPY', lf:'2025-02-24', lat:37.43, lng:-121.9},
  {t:'NANYA', n:'Nanya Technology', s:'semis', co:'TW', tr:true, p:'2408.TW', bm:'^TWII', lf:null, lat:24.99, lng:121.37},
  {t:'HANMI', n:'Hanmi Semiconductor', s:'semis', co:'KR', tr:true, p:'042700.KS', bm:'^KS11', lf:null, lat:37.46, lng:126.71},
  {t:'BESI', n:'BE Semiconductor (Besi)', s:'semis', co:'NL', tr:true, p:'BESI.AS', bm:'^STOXX50E', lf:null, lat:51.95, lng:6.02},
  {t:'XOM', n:'ExxonMobil', s:'energy', co:'US', tr:true, p:'XOM', bm:'SPY', lf:'1980-01-02', lat:30.08, lng:-95.42},
  {t:'MP', n:'MP Materials', s:'materials', co:'US', tr:true, p:'MP', bm:'SPY', lf:'2020-11-18', lat:36.17, lng:-115.14},
  {t:'FCX', n:'Freeport-McMoRan', s:'materials', co:'US', tr:true, p:'FCX', bm:'SPY', lf:'1995-07-10', lat:33.45, lng:-112.07}
] AS c
MERGE (x:Company {ticker:c.t})
  SET x.name = c.n, x.sector = c.s, x.country = c.co,
      x.tradable = c.tr, x.priceTicker = c.p, x.benchmark = c.bm, x.listedFrom = c.lf,
      x.lat = c.lat, x.lng = c.lng;

// ---------- Exposure scalars (macro-anchor companies) ----------
UNWIND [
  {t:'NVDA', chinaRev:0.13, taiwanOps:0.1, usRev:0.45, euRev:0.12, rateBeta:-0.7, fxBetaUSD:-0.3, policyBeta:-0.6},
  {t:'TSMC', chinaRev:0.1, taiwanOps:0.92, usRev:0.65, euRev:0.06, rateBeta:-0.4, fxBetaUSD:0.4, policyBeta:-0.25},
  {t:'ASML', chinaRev:0.29, taiwanOps:0, usRev:0.12, euRev:0.1, rateBeta:-0.6, fxBetaUSD:0.2, policyBeta:-0.5},
  {t:'AMD', chinaRev:0.15, taiwanOps:0.1, usRev:0.4, euRev:0.1, rateBeta:-0.65, fxBetaUSD:-0.2, policyBeta:-0.4},
  {t:'INTC', chinaRev:0.27, taiwanOps:0.1, usRev:0.3, euRev:0.1, rateBeta:-0.3, fxBetaUSD:-0.15, policyBeta:-0.15},
  {t:'MU', chinaRev:0.15, taiwanOps:0.15, usRev:0.2, euRev:0.08, rateBeta:-0.5, fxBetaUSD:-0.15, policyBeta:-0.3},
  {t:'AVGO', chinaRev:0.2, taiwanOps:0.1, usRev:0.4, euRev:0.1, rateBeta:-0.55, fxBetaUSD:-0.2, policyBeta:-0.3},
  {t:'QCOM', chinaRev:0.46, taiwanOps:0.1, usRev:0.05, euRev:0.05, rateBeta:-0.5, fxBetaUSD:-0.2, policyBeta:-0.3},
  {t:'SMSN', chinaRev:0.3, taiwanOps:0, usRev:0.3, euRev:0.12, rateBeta:-0.3, fxBetaUSD:0.4, policyBeta:-0.15},
  {t:'SKH', chinaRev:0.3, taiwanOps:0, usRev:0.35, euRev:0.08, rateBeta:-0.4, fxBetaUSD:0.4, policyBeta:-0.2},
  {t:'BABA', chinaRev:0.85, taiwanOps:0, usRev:0.03, euRev:0.03, rateBeta:-0.4, fxBetaUSD:-0.3, policyBeta:0.1},
  {t:'AAPL', chinaRev:0.18, taiwanOps:0.05, usRev:0.43, euRev:0.25, rateBeta:-0.4, fxBetaUSD:-0.4, policyBeta:-0.1},
  {t:'TSLA', chinaRev:0.22, taiwanOps:0, usRev:0.47, euRev:0.2, rateBeta:-0.8, fxBetaUSD:-0.3, policyBeta:-0.05},
  {t:'GM', chinaRev:0, taiwanOps:0, usRev:0.8, euRev:0.02, rateBeta:-0.5, fxBetaUSD:0.1, policyBeta:0},
  {t:'BYD', chinaRev:0.7, taiwanOps:0, usRev:0, euRev:0.08, rateBeta:-0.3, fxBetaUSD:-0.1, policyBeta:0.2},
  {t:'V', chinaRev:0.02, taiwanOps:0, usRev:0.45, euRev:0.2, rateBeta:-0.2, fxBetaUSD:-0.2, policyBeta:0},
  {t:'MA', chinaRev:0.02, taiwanOps:0, usRev:0.32, euRev:0.25, rateBeta:-0.2, fxBetaUSD:-0.25, policyBeta:0},
  {t:'JPM', chinaRev:0.02, taiwanOps:0, usRev:0.78, euRev:0.1, rateBeta:0.6, fxBetaUSD:0.1, policyBeta:0},
  {t:'GS', chinaRev:0.03, taiwanOps:0, usRev:0.6, euRev:0.18, rateBeta:0.4, fxBetaUSD:0.05, policyBeta:0},
  {t:'SMIC', chinaRev:0.8, taiwanOps:0, usRev:0.12, euRev:0.03, rateBeta:-0.3, fxBetaUSD:-0.1, policyBeta:0.6},
  {t:'TENCENT', chinaRev:0.9, taiwanOps:0, usRev:0.02, euRev:0.02, rateBeta:-0.4, fxBetaUSD:-0.3, policyBeta:0.1},
  {t:'BIDU', chinaRev:0.92, taiwanOps:0, usRev:0.02, euRev:0.02, rateBeta:-0.45, fxBetaUSD:-0.3, policyBeta:0.15},
  {t:'XIAOMI', chinaRev:0.55, taiwanOps:0, usRev:0.02, euRev:0.18, rateBeta:-0.4, fxBetaUSD:-0.2, policyBeta:0.15},
  {t:'IFX.DE', chinaRev:0.27, taiwanOps:0, usRev:0.27, euRev:0.18, rateBeta:-0.4, fxBetaUSD:0.3, policyBeta:-0.15},
  {t:'STM', chinaRev:0.3, taiwanOps:0, usRev:0.18, euRev:0.25, rateBeta:-0.4, fxBetaUSD:0.3, policyBeta:-0.15},
  {t:'VST', chinaRev:0, taiwanOps:0, usRev:1, euRev:0, rateBeta:-0.2, fxBetaUSD:0, policyBeta:0.05},
  {t:'CEG', chinaRev:0, taiwanOps:0, usRev:1, euRev:0, rateBeta:-0.2, fxBetaUSD:0, policyBeta:0.05},
  {t:'TM', chinaRev:0.1, taiwanOps:0, usRev:0.3, euRev:0.1, rateBeta:-0.2, fxBetaUSD:0.3, policyBeta:0},
  {t:'NIO', chinaRev:0.9, taiwanOps:0, usRev:0, euRev:0.06, rateBeta:-0.7, fxBetaUSD:-0.3, policyBeta:0.15}
] AS e
MATCH (x:Company {ticker:e.t})
  SET x.chinaRev = e.chinaRev, x.taiwanOps = e.taiwanOps, x.usRev = e.usRev, x.euRev = e.euRev, x.rateBeta = e.rateBeta, x.fxBetaUSD = e.fxBetaUSD, x.policyBeta = e.policyBeta;

// ---------- Countries (context) + LOCATED_IN ----------
UNWIND [
  {code:'CA', name:'Canada', region:'North America', bloc:'NATO'},
  {code:'CH', name:'Switzerland', region:'Europe', bloc:'Neutral'},
  {code:'CN', name:'China', region:'Asia', bloc:'China-bloc'},
  {code:'DE', name:'Germany', region:'Europe', bloc:'EU'},
  {code:'FI', name:'Finland', region:'Europe', bloc:'EU'},
  {code:'FR', name:'France', region:'Europe', bloc:'EU'},
  {code:'GB', name:'United Kingdom', region:'Europe', bloc:'NATO'},
  {code:'JP', name:'Japan', region:'Asia', bloc:'US-aligned'},
  {code:'KR', name:'South Korea', region:'Asia', bloc:'US-aligned'},
  {code:'NL', name:'Netherlands', region:'Europe', bloc:'EU'},
  {code:'SE', name:'Sweden', region:'Europe', bloc:'EU'},
  {code:'TW', name:'Taiwan', region:'Asia', bloc:'US-aligned'},
  {code:'US', name:'United States', region:'North America', bloc:'NATO'}
] AS k
MERGE (x:Country {code:k.code}) SET x.name = k.name, x.region = k.region, x.bloc = k.bloc;

UNWIND [
  {t:'MSFT', c:'US'},
  {t:'NVDA', c:'US'},
  {t:'TSMC', c:'TW'},
  {t:'ASML', c:'NL'},
  {t:'AMD', c:'US'},
  {t:'INTC', c:'US'},
  {t:'MU', c:'US'},
  {t:'AVGO', c:'US'},
  {t:'QCOM', c:'US'},
  {t:'ARM', c:'GB'},
  {t:'TXN', c:'US'},
  {t:'MRVL', c:'US'},
  {t:'LRCX', c:'US'},
  {t:'AMAT', c:'US'},
  {t:'SMSN', c:'KR'},
  {t:'SKH', c:'KR'},
  {t:'AWS', c:'US'},
  {t:'GCP', c:'US'},
  {t:'ORCL', c:'US'},
  {t:'IBM', c:'US'},
  {t:'OPENAI', c:'US'},
  {t:'XAI', c:'US'},
  {t:'ANTHROPIC', c:'US'},
  {t:'PPLX', c:'US'},
  {t:'COHERE', c:'CA'},
  {t:'MISTRAL', c:'FR'},
  {t:'AMZN', c:'US'},
  {t:'GOOGL', c:'US'},
  {t:'META', c:'US'},
  {t:'NFLX', c:'US'},
  {t:'BABA', c:'CN'},
  {t:'GITHUB', c:'US'},
  {t:'AAPL', c:'US'},
  {t:'DELL', c:'US'},
  {t:'SMCI', c:'US'},
  {t:'ANET', c:'US'},
  {t:'CSCO', c:'US'},
  {t:'FOXCONN', c:'TW'},
  {t:'WDC', c:'US'},
  {t:'STX', c:'US'},
  {t:'TSLA', c:'US'},
  {t:'GM', c:'US'},
  {t:'BYD', c:'CN'},
  {t:'CATL', c:'CN'},
  {t:'PANA', c:'JP'},
  {t:'V', c:'US'},
  {t:'MA', c:'US'},
  {t:'PYPL', c:'US'},
  {t:'JPM', c:'US'},
  {t:'GS', c:'US'},
  {t:'4063.T', c:'JP'},
  {t:'3436.T', c:'JP'},
  {t:'ENTG', c:'US'},
  {t:'LIN', c:'GB'},
  {t:'AI.PA', c:'FR'},
  {t:'8035.T', c:'JP'},
  {t:'KLAC', c:'US'},
  {t:'6857.T', c:'JP'},
  {t:'6920.T', c:'JP'},
  {t:'ASM.AS', c:'NL'},
  {t:'SNPS', c:'US'},
  {t:'CDNS', c:'US'},
  {t:'SMIC', c:'CN'},
  {t:'HUAHONG', c:'CN'},
  {t:'TENCENT', c:'CN'},
  {t:'BIDU', c:'CN'},
  {t:'XIAOMI', c:'CN'},
  {t:'JD', c:'CN'},
  {t:'NAVER', c:'KR'},
  {t:'KIOXIA', c:'JP'},
  {t:'IFX.DE', c:'DE'},
  {t:'STM', c:'CH'},
  {t:'NXPI', c:'NL'},
  {t:'SAP', c:'DE'},
  {t:'SIE.DE', c:'DE'},
  {t:'SU.PA', c:'FR'},
  {t:'NOK', c:'FI'},
  {t:'ERIC', c:'SE'},
  {t:'VST', c:'US'},
  {t:'CEG', c:'US'},
  {t:'NRG', c:'US'},
  {t:'GEV', c:'US'},
  {t:'ETN', c:'US'},
  {t:'VRT', c:'US'},
  {t:'PWR', c:'US'},
  {t:'F', c:'US'},
  {t:'RIVN', c:'US'},
  {t:'TM', c:'JP'},
  {t:'VOW3', c:'DE'},
  {t:'NIO', c:'CN'},
  {t:'LI', c:'CN'},
  {t:'LGES', c:'KR'},
  {t:'ALB', c:'US'},
  {t:'RXRX', c:'US'},
  {t:'SDGR', c:'US'},
  {t:'ILMN', c:'US'},
  {t:'TEM', c:'US'},
  {t:'SNDK', c:'US'},
  {t:'NANYA', c:'TW'},
  {t:'HANMI', c:'KR'},
  {t:'BESI', c:'NL'},
  {t:'XOM', c:'US'},
  {t:'MP', c:'US'},
  {t:'FCX', c:'US'}
] AS m
MATCH (c:Company {ticker:m.t}),(k:Country {code:m.c})
MERGE (c)-[:LOCATED_IN]->(k);

// ---------- Sectors (context, NOT traversed) + IN_SECTOR ----------
UNWIND ['ai', 'automotive', 'cloud', 'energy', 'finance', 'hardware', 'healthcare', 'internet', 'materials', 'semis'] AS sname
MERGE (s:Sector {name:sname});

UNWIND [
  {t:'MSFT', s:'cloud'},
  {t:'NVDA', s:'semis'},
  {t:'TSMC', s:'semis'},
  {t:'ASML', s:'semis'},
  {t:'AMD', s:'semis'},
  {t:'INTC', s:'semis'},
  {t:'MU', s:'semis'},
  {t:'AVGO', s:'semis'},
  {t:'QCOM', s:'semis'},
  {t:'ARM', s:'semis'},
  {t:'TXN', s:'semis'},
  {t:'MRVL', s:'semis'},
  {t:'LRCX', s:'semis'},
  {t:'AMAT', s:'semis'},
  {t:'SMSN', s:'semis'},
  {t:'SKH', s:'semis'},
  {t:'AWS', s:'cloud'},
  {t:'GCP', s:'cloud'},
  {t:'ORCL', s:'cloud'},
  {t:'IBM', s:'cloud'},
  {t:'OPENAI', s:'ai'},
  {t:'XAI', s:'ai'},
  {t:'ANTHROPIC', s:'ai'},
  {t:'PPLX', s:'ai'},
  {t:'COHERE', s:'ai'},
  {t:'MISTRAL', s:'ai'},
  {t:'AMZN', s:'internet'},
  {t:'GOOGL', s:'internet'},
  {t:'META', s:'internet'},
  {t:'NFLX', s:'internet'},
  {t:'BABA', s:'internet'},
  {t:'GITHUB', s:'internet'},
  {t:'AAPL', s:'hardware'},
  {t:'DELL', s:'hardware'},
  {t:'SMCI', s:'hardware'},
  {t:'ANET', s:'hardware'},
  {t:'CSCO', s:'hardware'},
  {t:'FOXCONN', s:'hardware'},
  {t:'WDC', s:'hardware'},
  {t:'STX', s:'hardware'},
  {t:'TSLA', s:'automotive'},
  {t:'GM', s:'automotive'},
  {t:'BYD', s:'automotive'},
  {t:'CATL', s:'automotive'},
  {t:'PANA', s:'automotive'},
  {t:'V', s:'finance'},
  {t:'MA', s:'finance'},
  {t:'PYPL', s:'finance'},
  {t:'JPM', s:'finance'},
  {t:'GS', s:'finance'},
  {t:'4063.T', s:'semis'},
  {t:'3436.T', s:'semis'},
  {t:'ENTG', s:'semis'},
  {t:'LIN', s:'semis'},
  {t:'AI.PA', s:'semis'},
  {t:'8035.T', s:'semis'},
  {t:'KLAC', s:'semis'},
  {t:'6857.T', s:'semis'},
  {t:'6920.T', s:'semis'},
  {t:'ASM.AS', s:'semis'},
  {t:'SNPS', s:'semis'},
  {t:'CDNS', s:'semis'},
  {t:'SMIC', s:'semis'},
  {t:'HUAHONG', s:'semis'},
  {t:'TENCENT', s:'internet'},
  {t:'BIDU', s:'ai'},
  {t:'XIAOMI', s:'hardware'},
  {t:'JD', s:'internet'},
  {t:'NAVER', s:'internet'},
  {t:'KIOXIA', s:'semis'},
  {t:'IFX.DE', s:'semis'},
  {t:'STM', s:'semis'},
  {t:'NXPI', s:'semis'},
  {t:'SAP', s:'cloud'},
  {t:'SIE.DE', s:'hardware'},
  {t:'SU.PA', s:'energy'},
  {t:'NOK', s:'hardware'},
  {t:'ERIC', s:'hardware'},
  {t:'VST', s:'energy'},
  {t:'CEG', s:'energy'},
  {t:'NRG', s:'energy'},
  {t:'GEV', s:'energy'},
  {t:'ETN', s:'energy'},
  {t:'VRT', s:'energy'},
  {t:'PWR', s:'energy'},
  {t:'F', s:'automotive'},
  {t:'RIVN', s:'automotive'},
  {t:'TM', s:'automotive'},
  {t:'VOW3', s:'automotive'},
  {t:'NIO', s:'automotive'},
  {t:'LI', s:'automotive'},
  {t:'LGES', s:'automotive'},
  {t:'ALB', s:'energy'},
  {t:'RXRX', s:'healthcare'},
  {t:'SDGR', s:'healthcare'},
  {t:'ILMN', s:'healthcare'},
  {t:'TEM', s:'healthcare'},
  {t:'SNDK', s:'semis'},
  {t:'NANYA', s:'semis'},
  {t:'HANMI', s:'semis'},
  {t:'BESI', s:'semis'},
  {t:'XOM', s:'energy'},
  {t:'MP', s:'materials'},
  {t:'FCX', s:'materials'}
] AS m
MATCH (c:Company {ticker:m.t}),(s:Sector {name:m.s})
MERGE (c)-[:IN_SECTOR]->(s);

// ---------- SUPPLIES_TO {criticality}  (supplier -> customer) ----------
UNWIND [
  {a:'NVDA', b:'MSFT', w:0.8},
  {a:'AMD', b:'MSFT', w:0.35},
  {a:'NVDA', b:'AWS', w:0.75},
  {a:'NVDA', b:'GCP', w:0.7},
  {a:'NVDA', b:'META', w:0.55},
  {a:'AMD', b:'AWS', w:0.25},
  {a:'INTC', b:'AWS', w:0.2},
  {a:'AVGO', b:'AWS', w:0.45},
  {a:'AVGO', b:'GCP', w:0.35},
  {a:'AWS', b:'ANTHROPIC', w:0.7},
  {a:'GCP', b:'COHERE', w:0.5},
  {a:'AWS', b:'PPLX', w:0.4},
  {a:'MSFT', b:'PPLX', w:0.35},
  {a:'MSFT', b:'OPENAI', w:0.75},
  {a:'TSMC', b:'NVDA', w:0.9},
  {a:'TSMC', b:'AMD', w:0.6},
  {a:'TSMC', b:'AAPL', w:0.4},
  {a:'TSMC', b:'INTC', w:0.4},
  {a:'TSMC', b:'QCOM', w:0.5},
  {a:'TSMC', b:'AVGO', w:0.5},
  {a:'TSMC', b:'MRVL', w:0.5},
  {a:'ASML', b:'TSMC', w:0.7},
  {a:'ASML', b:'INTC', w:0.45},
  {a:'ASML', b:'SMSN', w:0.45},
  {a:'LRCX', b:'TSMC', w:0.6},
  {a:'AMAT', b:'TSMC', w:0.6},
  {a:'AMAT', b:'INTC', w:0.5},
  {a:'LRCX', b:'SMSN', w:0.5},
  {a:'SKH', b:'NVDA', w:0.5},
  {a:'MU', b:'NVDA', w:0.45},
  {a:'SMSN', b:'NVDA', w:0.35},
  {a:'ARM', b:'AAPL', w:0.2},
  {a:'ARM', b:'QCOM', w:0.4},
  {a:'SMSN', b:'AAPL', w:0.45},
  {a:'FOXCONN', b:'AAPL', w:0.7},
  {a:'TXN', b:'AAPL', w:0.2},
  {a:'NVDA', b:'DELL', w:0.6},
  {a:'NVDA', b:'SMCI', w:0.7},
  {a:'AMD', b:'DELL', w:0.4},
  {a:'INTC', b:'DELL', w:0.5},
  {a:'AMD', b:'SMCI', w:0.4},
  {a:'AVGO', b:'CSCO', w:0.5},
  {a:'AVGO', b:'ANET', w:0.6},
  {a:'MRVL', b:'AWS', w:0.4},
  {a:'ANET', b:'META', w:0.5},
  {a:'NVDA', b:'TSLA', w:0.35},
  {a:'TXN', b:'TSLA', w:0.3},
  {a:'QCOM', b:'GM', w:0.3},
  {a:'CATL', b:'TSLA', w:0.65},
  {a:'PANA', b:'TSLA', w:0.55},
  {a:'CATL', b:'BYD', w:0.3},
  {a:'WDC', b:'AWS', w:0.35},
  {a:'STX', b:'AWS', w:0.3},
  {a:'WDC', b:'MSFT', w:0.25},
  {a:'AWS', b:'NFLX', w:0.35},
  {a:'AWS', b:'JPM', w:0.2},
  {a:'MSFT', b:'GS', w:0.2},
  {a:'4063.T', b:'TSMC', w:0.8},
  {a:'4063.T', b:'SMSN', w:0.7},
  {a:'4063.T', b:'INTC', w:0.6},
  {a:'3436.T', b:'TSMC', w:0.7},
  {a:'3436.T', b:'MU', w:0.6},
  {a:'3436.T', b:'SKH', w:0.5},
  {a:'ENTG', b:'TSMC', w:0.6},
  {a:'ENTG', b:'INTC', w:0.5},
  {a:'ENTG', b:'SMSN', w:0.5},
  {a:'LIN', b:'TSMC', w:0.7},
  {a:'LIN', b:'INTC', w:0.6},
  {a:'LIN', b:'MU', w:0.5},
  {a:'AI.PA', b:'TSMC', w:0.6},
  {a:'AI.PA', b:'SMSN', w:0.5},
  {a:'8035.T', b:'TSMC', w:0.8},
  {a:'8035.T', b:'SMSN', w:0.7},
  {a:'8035.T', b:'INTC', w:0.6},
  {a:'KLAC', b:'TSMC', w:0.8},
  {a:'KLAC', b:'SMSN', w:0.6},
  {a:'KLAC', b:'INTC', w:0.6},
  {a:'6857.T', b:'TSMC', w:0.7},
  {a:'6857.T', b:'NVDA', w:0.6},
  {a:'6857.T', b:'SMSN', w:0.5},
  {a:'6920.T', b:'TSMC', w:0.7},
  {a:'6920.T', b:'SMSN', w:0.6},
  {a:'6920.T', b:'INTC', w:0.5},
  {a:'ASM.AS', b:'TSMC', w:0.7},
  {a:'ASM.AS', b:'INTC', w:0.6},
  {a:'ASM.AS', b:'SMSN', w:0.5},
  {a:'SNPS', b:'NVDA', w:0.7},
  {a:'SNPS', b:'AMD', w:0.6},
  {a:'SNPS', b:'QCOM', w:0.6},
  {a:'SNPS', b:'TSMC', w:0.6},
  {a:'SNPS', b:'ARM', w:0.4},
  {a:'CDNS', b:'NVDA', w:0.6},
  {a:'CDNS', b:'AMD', w:0.6},
  {a:'CDNS', b:'MRVL', w:0.6},
  {a:'CDNS', b:'TSMC', w:0.5},
  {a:'AMAT', b:'SMIC', w:0.5},
  {a:'LRCX', b:'SMIC', w:0.5},
  {a:'AMAT', b:'HUAHONG', w:0.4},
  {a:'NVDA', b:'TENCENT', w:0.4},
  {a:'NVDA', b:'BIDU', w:0.4},
  {a:'QCOM', b:'XIAOMI', w:0.7},
  {a:'TSMC', b:'XIAOMI', w:0.4},
  {a:'IFX.DE', b:'TSLA', w:0.6},
  {a:'IFX.DE', b:'GM', w:0.5},
  {a:'IFX.DE', b:'BYD', w:0.5},
  {a:'TSMC', b:'IFX.DE', w:0.4},
  {a:'STM', b:'TSLA', w:0.6},
  {a:'STM', b:'AAPL', w:0.4},
  {a:'TSMC', b:'STM', w:0.3},
  {a:'NXPI', b:'TSLA', w:0.5},
  {a:'NXPI', b:'GM', w:0.5},
  {a:'TSMC', b:'NXPI', w:0.4},
  {a:'SU.PA', b:'AWS', w:0.3},
  {a:'SU.PA', b:'MSFT', w:0.25},
  {a:'SU.PA', b:'GCP', w:0.25},
  {a:'SU.PA', b:'META', w:0.25},
  {a:'SIE.DE', b:'MSFT', w:0.2},
  {a:'SIE.DE', b:'AWS', w:0.2},
  {a:'CEG', b:'MSFT', w:0.55},
  {a:'VST', b:'META', w:0.55},
  {a:'VRT', b:'AWS', w:0.55},
  {a:'VRT', b:'GCP', w:0.45},
  {a:'VRT', b:'META', w:0.45},
  {a:'VRT', b:'DELL', w:0.35},
  {a:'VRT', b:'SMCI', w:0.35},
  {a:'ETN', b:'AWS', w:0.5},
  {a:'ETN', b:'GCP', w:0.4},
  {a:'ETN', b:'MSFT', w:0.25},
  {a:'GEV', b:'NRG', w:0.55},
  {a:'GEV', b:'VST', w:0.5},
  {a:'GEV', b:'CEG', w:0.45},
  {a:'GEV', b:'AWS', w:0.35},
  {a:'PWR', b:'VST', w:0.4},
  {a:'PWR', b:'CEG', w:0.4},
  {a:'PWR', b:'GEV', w:0.35},
  {a:'LGES', b:'TSLA', w:0.4},
  {a:'LGES', b:'GM', w:0.8},
  {a:'LGES', b:'F', w:0.5},
  {a:'LGES', b:'RIVN', w:0.5},
  {a:'LGES', b:'VOW3', w:0.4},
  {a:'CATL', b:'NIO', w:0.7},
  {a:'CATL', b:'LI', w:0.6},
  {a:'CATL', b:'F', w:0.4},
  {a:'CATL', b:'VOW3', w:0.4},
  {a:'PANA', b:'TM', w:0.5},
  {a:'ALB', b:'TSLA', w:0.4},
  {a:'QCOM', b:'F', w:0.3},
  {a:'QCOM', b:'VOW3', w:0.4},
  {a:'NVDA', b:'LI', w:0.4},
  {a:'HANMI', b:'SKH', w:0.8},
  {a:'HANMI', b:'SMSN', w:0.5},
  {a:'BESI', b:'SKH', w:0.5},
  {a:'BESI', b:'TSMC', w:0.5},
  {a:'LRCX', b:'MU', w:0.55},
  {a:'LRCX', b:'SKH', w:0.5},
  {a:'AMAT', b:'MU', w:0.5},
  {a:'8035.T', b:'SKH', w:0.5},
  {a:'6857.T', b:'MU', w:0.5},
  {a:'ENTG', b:'SKH', w:0.4},
  {a:'MSFT', b:'MISTRAL', w:0.35}
] AS e
MATCH (s:Company {ticker:e.a}),(d:Company {ticker:e.b})
MERGE (s)-[r:SUPPLIES_TO]->(d) SET r.criticality = e.w;

// ---------- PARTNERS_WITH {strength}  (partnership) ----------
UNWIND [
  {a:'MSFT', b:'OPENAI', w:0.85},
  {a:'AWS', b:'ANTHROPIC', w:0.6},
  {a:'GCP', b:'COHERE', w:0.45},
  {a:'XAI', b:'TSLA', w:0.35},
  {a:'AAPL', b:'V', w:0.3},
  {a:'AAPL', b:'GS', w:0.3},
  {a:'V', b:'JPM', w:0.4},
  {a:'8035.T', b:'ASML', w:0.6},
  {a:'6920.T', b:'ASML', w:0.5},
  {a:'KIOXIA', b:'WDC', w:0.8},
  {a:'SAP', b:'AWS', w:0.5},
  {a:'SIE.DE', b:'NVDA', w:0.4},
  {a:'TEM', b:'RXRX', w:0.3},
  {a:'BESI', b:'AMAT', w:0.6}
] AS e
MATCH (s:Company {ticker:e.a}),(d:Company {ticker:e.b})
MERGE (s)-[r:PARTNERS_WITH]->(d) SET r.strength = e.w;

// ---------- OWNS {pct}  (parent -> subsidiary (pct)) ----------
UNWIND [
  {a:'AMZN', b:'AWS', w:100},
  {a:'GOOGL', b:'GCP', w:100},
  {a:'MSFT', b:'GITHUB', w:100},
  {a:'TENCENT', b:'JD', w:2}
] AS e
MATCH (s:Company {ticker:e.a}),(d:Company {ticker:e.b})
MERGE (s)-[r:OWNS]->(d) SET r.pct = e.w;

// ---------- COMPETES_WITH {overlap}  (rivalry (sign-flipping channel)) ----------
UNWIND [
  {a:'NVDA', b:'AMD', w:0.55},
  {a:'NVDA', b:'INTC', w:0.35},
  {a:'AMD', b:'INTC', w:0.5},
  {a:'TSMC', b:'SMSN', w:0.5},
  {a:'TSMC', b:'INTC', w:0.4},
  {a:'SMSN', b:'INTC', w:0.3},
  {a:'AAPL', b:'SMSN', w:0.65},
  {a:'MU', b:'SMSN', w:0.55},
  {a:'MU', b:'SKH', w:0.55},
  {a:'WDC', b:'STX', w:0.8},
  {a:'LRCX', b:'AMAT', w:0.6},
  {a:'MRVL', b:'AVGO', w:0.6},
  {a:'TXN', b:'QCOM', w:0.25},
  {a:'CSCO', b:'ANET', w:0.7},
  {a:'DELL', b:'SMCI', w:0.6},
  {a:'TSLA', b:'BYD', w:0.7},
  {a:'GM', b:'TSLA', w:0.5},
  {a:'AWS', b:'GCP', w:0.6},
  {a:'ORCL', b:'AWS', w:0.45},
  {a:'IBM', b:'ORCL', w:0.5},
  {a:'IBM', b:'MSFT', w:0.4},
  {a:'OPENAI', b:'ANTHROPIC', w:0.6},
  {a:'MSFT', b:'GOOGL', w:0.5},
  {a:'MSFT', b:'AMZN', w:0.45},
  {a:'BABA', b:'AMZN', w:0.6},
  {a:'V', b:'MA', w:0.8},
  {a:'V', b:'PYPL', w:0.5},
  {a:'MA', b:'PYPL', w:0.45},
  {a:'JPM', b:'GS', w:0.7},
  {a:'3436.T', b:'4063.T', w:0.7},
  {a:'AI.PA', b:'LIN', w:0.7},
  {a:'8035.T', b:'LRCX', w:0.7},
  {a:'8035.T', b:'AMAT', w:0.5},
  {a:'KLAC', b:'AMAT', w:0.5},
  {a:'ASM.AS', b:'AMAT', w:0.5},
  {a:'CDNS', b:'SNPS', w:0.7},
  {a:'SMIC', b:'TSMC', w:0.5},
  {a:'HUAHONG', b:'SMIC', w:0.6},
  {a:'TENCENT', b:'AWS', w:0.4},
  {a:'TENCENT', b:'BABA', w:0.5},
  {a:'BIDU', b:'GOOGL', w:0.5},
  {a:'BIDU', b:'OPENAI', w:0.4},
  {a:'XIAOMI', b:'AAPL', w:0.5},
  {a:'XIAOMI', b:'SMSN', w:0.6},
  {a:'JD', b:'BABA', w:0.7},
  {a:'NAVER', b:'GOOGL', w:0.4},
  {a:'KIOXIA', b:'SMSN', w:0.7},
  {a:'KIOXIA', b:'MU', w:0.7},
  {a:'KIOXIA', b:'SKH', w:0.7},
  {a:'SAP', b:'ORCL', w:0.7},
  {a:'SAP', b:'MSFT', w:0.5},
  {a:'NOK', b:'CSCO', w:0.5},
  {a:'NOK', b:'ANET', w:0.3},
  {a:'ERIC', b:'NOK', w:0.7},
  {a:'ERIC', b:'CSCO', w:0.3},
  {a:'VST', b:'CEG', w:0.7},
  {a:'VST', b:'NRG', w:0.55},
  {a:'CEG', b:'NRG', w:0.45},
  {a:'ETN', b:'VRT', w:0.45},
  {a:'RIVN', b:'TSLA', w:0.7},
  {a:'RIVN', b:'GM', w:0.5},
  {a:'F', b:'GM', w:0.7},
  {a:'F', b:'TSLA', w:0.5},
  {a:'TM', b:'GM', w:0.7},
  {a:'VOW3', b:'TSLA', w:0.5},
  {a:'VOW3', b:'BYD', w:0.5},
  {a:'NIO', b:'BYD', w:0.7},
  {a:'NIO', b:'LI', w:0.7},
  {a:'LI', b:'TSLA', w:0.5},
  {a:'LGES', b:'CATL', w:0.7},
  {a:'LGES', b:'PANA', w:0.5},
  {a:'F', b:'TM', w:0.5},
  {a:'RXRX', b:'SDGR', w:0.5},
  {a:'SNDK', b:'KIOXIA', w:0.7},
  {a:'SNDK', b:'MU', w:0.45},
  {a:'NANYA', b:'MU', w:0.5},
  {a:'NANYA', b:'SKH', w:0.4},
  {a:'HANMI', b:'BESI', w:0.4},
  {a:'MISTRAL', b:'OPENAI', w:0.5}
] AS e
MATCH (s:Company {ticker:e.a}),(d:Company {ticker:e.b})
MERGE (s)-[r:COMPETES_WITH]->(d) SET r.overlap = e.w;

// ---------- Commodity nodes (seed-only) ----------
UNWIND [
  {id:'NEON', name:'Neon (semiconductor-grade)', category:'industrial_gas', geo:'Ukraine ~70% of global semiconductor-grade supply (Ingas/Cryoin, Odesa & Mariupol); purified as a steelmaking byproduct, much feedstock historically from Russia/China. China is the other large producer.'},
  {id:'ELECTRICITY', name:'Wholesale electricity / power', category:'energy', geo:'Regional/grid-bound (not globally traded); US merchant power concentrated in PJM/ERCOT. Datacenter-driven demand growth is the swing factor.'},
  {id:'CRUDE', name:'Crude oil', category:'energy', geo:'Globally traded (Brent/WTI); supply concentrated in OPEC+ (~40% of output), US shale, and Russia.'},
  {id:'LITHIUM', name:'Lithium', category:'battery_metal', geo:'Mining: Australia ~50%, Chile + Argentina (lithium triangle) ~25%; refining/processing China ~65-70%.'},
  {id:'RARE_EARTH', name:'Rare earth elements (NdPr / magnet)', category:'critical_mineral', geo:'China ~70% of mining and ~85-90% of refining/separation; MP Materials (Mountain Pass) is the main ex-China mine (~15% of global content).'}
] AS m
MERGE (x:Commodity {id:m.id}) SET x.name = m.name, x.category = m.category, x.geoConcentration = m.geo;

// ---------- Theme nodes (seed-only) ----------
UNWIND [
  {id:'AI-capex', name:'AI Datacenter Capex', kind:'narrative', desc:'The hyperscaler/sovereign AI infrastructure build-out thesis. Names move on the expectation of sustained, rising spend on AI accelerators, custom silicon, networking and full racks. This is the basket that DeepSeek (2025-01-27) re-rated: a cheap-compute shock that questions the capex trajectory hits every member, even those with no direct DeepSeek linkage. Sign +1 means the stock rises when the AI-capex narrative strengthens.'},
  {id:'HBM-memory', name:'High-Bandwidth Memory (HBM) Cycle', kind:'narrative', desc:'The AI-memory super-cycle: HBM (stacked DRAM for AI accelerators) plus the back-end packaging tools (TC bonders, hybrid bonding) that gate HBM supply. A sub-narrative of AI-capex but with its own pricing/supply dynamics (HBM is sold out, ASP-rich, and capacity-constrained), so members can decouple from broad logic. Sign +1: stock rises when HBM demand/pricing tightens.'},
  {id:'AI-power-demand', name:'AI Power Demand', kind:'narrative', desc:'The \'electricity is the bottleneck for AI\' thesis: independent power producers (esp. nuclear), grid/transmission build-out, and datacenter electrical/cooling/backup gear all re-rate on expectations that AI datacenters drive a step-change in US power demand. Sign +1: stock rises as the power-demand narrative strengthens. BEAR CASE: this theme is structurally DOWNSTREAM of AI-capex — if AI capex disappoints (a DeepSeek-style efficiency shock, or a hyperscaler capex cut), the power-demand thesis deflates too, so members also carry positive AI-capex loadings and can sell off in an AI de-rating despite no fundamental change in current power load.'},
  {id:'export-control', name:'US-China Semiconductor Export Controls', kind:'style_factor', desc:'Policy-risk factor for the US/allied chip & equipment complex exposed to China-revenue restrictions vs. the Chinese domestic champions that benefit from forced import-substitution. A TIGHTENING of controls is the shock: Western accelerator and WFE (wafer-fab-equipment) makers lose addressable China demand (sign -1), while protected, state-backed Chinese foundries gain share and subsidy (sign +1). Loadings reflect China-revenue / China-orderbook transmission, not operational dependency.'},
  {id:'China-tech', name:'China Tech / ADR Basket', kind:'style_factor', desc:'The China internet + domestic-chip basket beta: US-listed ADRs and HK-listed China-tech names that move together on China macro/regulatory risk-on/risk-off (stimulus, regulatory thaw, delisting/geopolitical headlines). Sign +1: stock rises on a China-tech re-rating (e.g. the Sep-2024 PBOC stimulus rally). Captures common basket factor exposure that no company-to-company edge expresses.'},
  {id:'EV-transition', name:'EV Transition', kind:'narrative', desc:'The global shift to battery-electric vehicles and its battery/materials supply chain. Pure-play EV makers, battery cell manufacturers and lithium producers re-rate on EV demand/penetration expectations, price wars, and subsidy/policy shifts. Sign +1: stock rises as EV-transition momentum strengthens. Note the embedded tension for legacy/diversified OEMs, where an aggressive EV transition is volume-positive but margin-dilutive (lower loading).'},
  {id:'AI-drug-discovery', name:'AI Drug Discovery / TechBio', kind:'narrative', desc:'The \'AI applied to biology\' thesis: computational drug discovery, AI-driven diagnostics/genomics, and platform TechBio names. A small, distinct sub-narrative of the broader AI trade — these stocks catch sentiment from AI-capex risk-on/risk-off but are NOT levered to hyperscaler accelerator spend, so they get a modest AI-capex loading plus a primary loading here rather than fake NVDA-supply edges. Sign +1: rises on AI-in-biology enthusiasm.'}
] AS t
MERGE (x:Theme {id:t.id}) SET x.name = t.name, x.kind = t.kind, x.description = t.desc;

// ---------- Condition nodes (standing state — seed-only) ----------
UNWIND [
  {id:'cond_us_china_chip_controls', kind:'export_control', status:'active', sd:'2022-10-07', ed:null, jur:'US', dom:'semiconductors', sev:0.7, desc:'US Bureau of Industry and Security (BIS) advanced-computing & semiconductor-manufacturing export controls on China, enacted 2022-10-07. Bans export of leading-edge AI accelerators (A100/H100 class) and advanced wafer-fab equipment (EUV/advanced DUV, advanced etch/deposition/metrology) to Chinese fabs; restricts US-person support. Tightened 2023-10-17 (A800/H800/L40 loophole closure) and again Dec-2024. Hurts US/EU chip and WFE exporters that lose China revenue; helps Chinese domestic foundries (SMIC, Hua Hong) via forced localization / self-sufficiency demand.'},
  {id:'cond_us_china_tariffs', kind:'tariff', status:'active', sd:'2018-07-06', ed:null, jur:'US', dom:'trade', sev:0.4, desc:'US Section 301 tariffs on Chinese imports, first effective 2018-07-06 (List 1, 25%) and progressively broadened; still active. Hurts US firms with China-manufactured hardware or large China import/revenue exposure (Apple supply chain, autos, EV-component imports) and Chinese exporters into the US; a renewed/expanded China-tariff stance under the 2024 Trump win is the policy overhang re-priced by markets.'}
] AS d
MERGE (x:Condition {id:d.id})
  SET x.kind=d.kind, x.status=d.status, x.startDate=d.sd, x.endDate=d.ed,
      x.jurisdiction=d.jur, x.domain=d.dom, x.severity=d.sev, x.description=d.desc;

// ---------- REVENUE_FROM (seed-only exposure) ----------
UNWIND [
  {a:'NVDA', b:'US', v:0.45, sg:1, ch:'demand', src:'10-K:NVDA'},
  {a:'NVDA', b:'CN', v:0.13, sg:1, ch:'demand', src:'10-K:NVDA'},
  {a:'NVDA', b:'TW', v:0.2, sg:1, ch:'demand', src:'10-K:NVDA'},
  {a:'TSMC', b:'US', v:0.65, sg:1, ch:'demand', src:'10-K:TSMC'},
  {a:'TSMC', b:'CN', v:0.1, sg:1, ch:'demand', src:'10-K:TSMC'},
  {a:'SMSN', b:'CN', v:0.3, sg:1, ch:'demand', src:'public'},
  {a:'SMSN', b:'US', v:0.3, sg:1, ch:'demand', src:'public'},
  {a:'SKH', b:'CN', v:0.3, sg:1, ch:'demand', src:'public'},
  {a:'SKH', b:'US', v:0.35, sg:1, ch:'demand', src:'public'},
  {a:'AAPL', b:'US', v:0.43, sg:1, ch:'demand', src:'10-K:AAPL'},
  {a:'AAPL', b:'CN', v:0.18, sg:1, ch:'demand', src:'10-K:AAPL'},
  {a:'AAPL', b:'DE', v:0.25, sg:1, ch:'demand', src:'10-K:AAPL'},
  {a:'AMD', b:'US', v:0.4, sg:1, ch:'demand', src:'10-K:AMD'},
  {a:'AMD', b:'CN', v:0.15, sg:1, ch:'demand', src:'10-K:AMD'},
  {a:'AVGO', b:'US', v:0.4, sg:1, ch:'demand', src:'10-K:AVGO'},
  {a:'AVGO', b:'CN', v:0.2, sg:1, ch:'demand', src:'10-K:AVGO'},
  {a:'QCOM', b:'CN', v:0.46, sg:1, ch:'demand', src:'10-K:QCOM'},
  {a:'QCOM', b:'US', v:0.05, sg:1, ch:'demand', src:'10-K:QCOM'},
  {a:'MU', b:'US', v:0.2, sg:1, ch:'demand', src:'10-K:MU'},
  {a:'MU', b:'CN', v:0.15, sg:1, ch:'demand', src:'10-K:MU'},
  {a:'MU', b:'TW', v:0.25, sg:1, ch:'demand', src:'10-K:MU'},
  {a:'ASML', b:'CN', v:0.29, sg:1, ch:'demand', src:'10-K:ASML'},
  {a:'ASML', b:'TW', v:0.2, sg:1, ch:'demand', src:'10-K:ASML'},
  {a:'ASML', b:'KR', v:0.18, sg:1, ch:'demand', src:'10-K:ASML'},
  {a:'INTC', b:'US', v:0.3, sg:1, ch:'demand', src:'10-K:INTC'},
  {a:'INTC', b:'CN', v:0.27, sg:1, ch:'demand', src:'10-K:INTC'},
  {a:'BABA', b:'CN', v:0.85, sg:1, ch:'demand', src:'10-K:BABA'},
  {a:'TENCENT', b:'CN', v:0.9, sg:1, ch:'demand', src:'public'},
  {a:'SMIC', b:'CN', v:0.8, sg:1, ch:'demand', src:'public'},
  {a:'SMIC', b:'US', v:0.12, sg:1, ch:'demand', src:'public'},
  {a:'XIAOMI', b:'CN', v:0.55, sg:1, ch:'demand', src:'public'},
  {a:'XIAOMI', b:'DE', v:0.18, sg:1, ch:'demand', src:'public'},
  {a:'BIDU', b:'CN', v:0.92, sg:1, ch:'demand', src:'public'},
  {a:'TSLA', b:'US', v:0.47, sg:1, ch:'demand', src:'10-K:TSLA'},
  {a:'TSLA', b:'CN', v:0.22, sg:1, ch:'demand', src:'10-K:TSLA'},
  {a:'GM', b:'US', v:0.8, sg:1, ch:'demand', src:'10-K:GM'},
  {a:'BYD', b:'CN', v:0.7, sg:1, ch:'demand', src:'public'},
  {a:'NIO', b:'CN', v:0.9, sg:1, ch:'demand', src:'public'},
  {a:'TM', b:'US', v:0.3, sg:1, ch:'demand', src:'public'},
  {a:'TM', b:'JP', v:0.35, sg:1, ch:'demand', src:'public'},
  {a:'V', b:'US', v:0.45, sg:1, ch:'demand', src:'10-K:V'},
  {a:'MA', b:'US', v:0.32, sg:1, ch:'demand', src:'10-K:MA'},
  {a:'JPM', b:'US', v:0.78, sg:1, ch:'demand', src:'10-K:JPM'},
  {a:'GS', b:'US', v:0.6, sg:1, ch:'demand', src:'10-K:GS'},
  {a:'VST', b:'US', v:1, sg:1, ch:'demand', src:'public'},
  {a:'CEG', b:'US', v:1, sg:1, ch:'demand', src:'public'},
  {a:'IFX.DE', b:'CN', v:0.27, sg:1, ch:'demand', src:'public'},
  {a:'IFX.DE', b:'US', v:0.27, sg:1, ch:'demand', src:'public'},
  {a:'STM', b:'CN', v:0.3, sg:1, ch:'demand', src:'public'},
  {a:'STM', b:'US', v:0.18, sg:1, ch:'demand', src:'public'}
] AS e
MATCH (c:Company {ticker:e.a}),(n:Country {code:e.b})
MERGE (c)-[r:REVENUE_FROM]->(n) SET r.value=e.v, r.sign=e.sg, r.channel=e.ch, r.source=e.src;

// ---------- OPERATES_IN (seed-only exposure) ----------
UNWIND [
  {a:'NVDA', b:'US', v:0.7, sg:1, ch:null, src:'10-K:NVDA'},
  {a:'NVDA', b:'TW', v:0.1, sg:1, ch:null, src:'public'},
  {a:'TSMC', b:'TW', v:0.92, sg:1, ch:null, src:'10-K:TSMC'},
  {a:'TSMC', b:'US', v:0.05, sg:1, ch:null, src:'public'},
  {a:'SMSN', b:'KR', v:0.7, sg:1, ch:null, src:'public'},
  {a:'SMSN', b:'CN', v:0.15, sg:1, ch:null, src:'public'},
  {a:'SKH', b:'KR', v:0.7, sg:1, ch:null, src:'public'},
  {a:'SKH', b:'CN', v:0.2, sg:1, ch:null, src:'public'},
  {a:'AAPL', b:'CN', v:0.6, sg:1, ch:null, src:'public'},
  {a:'AAPL', b:'US', v:0.2, sg:1, ch:null, src:'public'},
  {a:'AMD', b:'US', v:0.6, sg:1, ch:null, src:'public'},
  {a:'AMD', b:'TW', v:0.1, sg:1, ch:null, src:'public'},
  {a:'AVGO', b:'US', v:0.6, sg:1, ch:null, src:'public'},
  {a:'QCOM', b:'US', v:0.6, sg:1, ch:null, src:'public'},
  {a:'MU', b:'US', v:0.4, sg:1, ch:null, src:'public'},
  {a:'MU', b:'TW', v:0.15, sg:1, ch:null, src:'public'},
  {a:'ASML', b:'NL', v:0.7, sg:1, ch:null, src:'public'},
  {a:'INTC', b:'US', v:0.55, sg:1, ch:null, src:'public'},
  {a:'BABA', b:'CN', v:0.9, sg:1, ch:null, src:'public'},
  {a:'TENCENT', b:'CN', v:0.9, sg:1, ch:null, src:'public'},
  {a:'SMIC', b:'CN', v:0.95, sg:1, ch:null, src:'public'},
  {a:'XIAOMI', b:'CN', v:0.85, sg:1, ch:null, src:'public'},
  {a:'BIDU', b:'CN', v:0.92, sg:1, ch:null, src:'public'},
  {a:'TSLA', b:'US', v:0.6, sg:1, ch:null, src:'public'},
  {a:'TSLA', b:'CN', v:0.25, sg:1, ch:null, src:'public'},
  {a:'GM', b:'US', v:0.75, sg:1, ch:null, src:'public'},
  {a:'BYD', b:'CN', v:0.9, sg:1, ch:null, src:'public'},
  {a:'NIO', b:'CN', v:0.9, sg:1, ch:null, src:'public'},
  {a:'TM', b:'JP', v:0.6, sg:1, ch:null, src:'public'},
  {a:'V', b:'US', v:0.7, sg:1, ch:null, src:'public'},
  {a:'MA', b:'US', v:0.65, sg:1, ch:null, src:'public'},
  {a:'JPM', b:'US', v:0.8, sg:1, ch:null, src:'public'},
  {a:'GS', b:'US', v:0.7, sg:1, ch:null, src:'public'},
  {a:'VST', b:'US', v:1, sg:1, ch:null, src:'public'},
  {a:'CEG', b:'US', v:1, sg:1, ch:null, src:'public'},
  {a:'IFX.DE', b:'DE', v:0.5, sg:1, ch:null, src:'public'},
  {a:'STM', b:'FR', v:0.35, sg:1, ch:null, src:'public'}
] AS e
MATCH (c:Company {ticker:e.a}),(n:Country {code:e.b})
MERGE (c)-[r:OPERATES_IN]->(n) SET r.value=e.v, r.sign=e.sg, r.channel=e.ch, r.source=e.src;

// ---------- EXPOSED_TO_POLICY (seed-only exposure) ----------
UNWIND [
  {a:'NVDA', b:'US', v:-0.6, sg:1, ch:'policy', src:'public'},
  {a:'NVDA', b:'CN', v:-0.4, sg:1, ch:'policy', src:'public'},
  {a:'TSMC', b:'US', v:-0.25, sg:1, ch:'policy', src:'public'},
  {a:'SMSN', b:'US', v:-0.15, sg:1, ch:'policy', src:'public'},
  {a:'SKH', b:'US', v:-0.2, sg:1, ch:'policy', src:'public'},
  {a:'AMD', b:'US', v:-0.4, sg:1, ch:'policy', src:'public'},
  {a:'AVGO', b:'US', v:-0.3, sg:1, ch:'policy', src:'public'},
  {a:'QCOM', b:'US', v:-0.3, sg:1, ch:'policy', src:'public'},
  {a:'MU', b:'CN', v:-0.3, sg:1, ch:'policy', src:'public'},
  {a:'ASML', b:'US', v:-0.5, sg:1, ch:'policy', src:'public'},
  {a:'INTC', b:'US', v:-0.15, sg:1, ch:'policy', src:'public'},
  {a:'SMIC', b:'CN', v:0.6, sg:1, ch:'policy', src:'public'},
  {a:'SMIC', b:'US', v:-0.3, sg:-1, ch:'policy', src:'public'},
  {a:'XIAOMI', b:'CN', v:0.15, sg:1, ch:'policy', src:'public'},
  {a:'BIDU', b:'CN', v:0.15, sg:1, ch:'policy', src:'public'},
  {a:'BYD', b:'CN', v:0.2, sg:1, ch:'policy', src:'public'},
  {a:'NIO', b:'CN', v:0.15, sg:1, ch:'policy', src:'public'},
  {a:'IFX.DE', b:'US', v:-0.15, sg:1, ch:'policy', src:'public'},
  {a:'STM', b:'US', v:-0.15, sg:1, ch:'policy', src:'public'}
] AS e
MATCH (c:Company {ticker:e.a}),(n:Country {code:e.b})
MERGE (c)-[r:EXPOSED_TO_POLICY]->(n) SET r.value=e.v, r.sign=e.sg, r.channel=e.ch, r.source=e.src;

// ---------- PRODUCES (seed-only exposure) ----------
UNWIND [
  {a:'XOM', b:'CRUDE', v:0.85, sg:1, ch:'commodity', src:'ExxonMobil is an integrated oil major; upstream earnings track crude prices, so XOM moves strongly same-sign with crude.'},
  {a:'MP', b:'RARE_EARTH', v:0.9, sg:1, ch:'commodity', src:'MP Materials is a near-pure-play NdPr/rare-earth producer (Mountain Pass); its equity is highly levered to rare-earth (esp. NdPr) prices.'},
  {a:'FCX', b:'RARE_EARTH', v:0.1, sg:1, ch:'commodity', src:'FCX is primarily a copper/gold producer (no commodity in this lite set); only a weak, indirect critical-minerals readthrough. Low weight, flagged as soft.'},
  {a:'LIN', b:'NEON', v:0.15, sg:1, ch:'commodity', src:'Linde is a top global industrial-gas major that purifies/sells semiconductor-grade neon, but neon is a tiny fraction of revenue; transmission to LIN stock is small (mostly a pricing-power tailwind during shortages).'},
  {a:'AI.PA', b:'NEON', v:0.15, sg:1, ch:'commodity', src:'Air Liquide is the other major industrial-gas producer of rare gases incl. neon; same as Linde, neon is immaterial to group revenue, so weak same-sign transmission.'},
  {a:'CEG', b:'ELECTRICITY', v:0.7, sg:1, ch:'commodity', src:'Constellation is the largest US nuclear/merchant-power generator; earnings and stock are highly levered to wholesale power prices (and datacenter PPA demand). Same-sign.'},
  {a:'VST', b:'ELECTRICITY', v:0.7, sg:1, ch:'commodity', src:'Vistra is a merchant power generator (gas/nuclear/solar); equity is a high-beta play on power prices and AI-datacenter demand. Same-sign.'},
  {a:'NRG', b:'ELECTRICITY', v:0.55, sg:1, ch:'commodity', src:'NRG is an integrated power/retail generator; levered to power prices but more hedged/retail-buffered than pure merchants, so somewhat lower transmission.'},
  {a:'ALB', b:'LITHIUM', v:0.85, sg:1, ch:'commodity', src:'Albemarle is the largest pure-play lithium producer; equity tracks lithium (spodumene/carbonate) prices very closely. Strong same-sign.'}
] AS e
MATCH (c:Company {ticker:e.a}),(n:Commodity {id:e.b})
MERGE (c)-[r:PRODUCES]->(n) SET r.value=e.v, r.sign=e.sg, r.channel=e.ch, r.source=e.src;

// ---------- CONSUMES (seed-only exposure) ----------
UNWIND [
  {a:'TSMC', b:'NEON', v:0.35, sg:-1, ch:'operations', src:'Neon is a key DUV excimer-laser lithography gas; a neon spike/shortage is an input-cost and supply-continuity risk for the leading-edge fab. War->neon->chips chain. Opposite-sign (cost up = bad).'},
  {a:'SMSN', b:'NEON', v:0.3, sg:-1, ch:'operations', src:'Large memory+logic fab; significant DUV-litho neon consumer. Input-cost/continuity risk on a neon shock.'},
  {a:'INTC', b:'NEON', v:0.28, sg:-1, ch:'operations', src:'IDM with large DUV-litho footprint; neon-shortage exposure on the cost/continuity side.'},
  {a:'MU', b:'NEON', v:0.28, sg:-1, ch:'operations', src:'DRAM/NAND fabs run heavy DUV lithography; neon-supply shock is an operational/cost risk.'},
  {a:'SKH', b:'NEON', v:0.28, sg:-1, ch:'operations', src:'SK hynix memory fabs are major DUV-litho neon consumers; opposite-sign cost/continuity exposure.'},
  {a:'MSFT', b:'ELECTRICITY', v:0.08, sg:-1, ch:'operations', src:'Datacenter power is a real and growing cost, but immaterial to MSFT margins today; weak opposite-sign cost transmission (power->datacenter chain). Low weight, honest.'},
  {a:'META', b:'ELECTRICITY', v:0.1, sg:-1, ch:'operations', src:'Heavy AI-datacenter power consumer; power cost is a growing but still small share of opex. Weak opposite-sign transmission.'},
  {a:'AWS', b:'ELECTRICITY', v:0.1, sg:-1, ch:'operations', src:'Largest hyperscale datacenter operator; rising power cost is a margin headwind but small vs total. Non-tradable node (propagates to AMZN). Weak opposite-sign.'},
  {a:'GCP', b:'ELECTRICITY', v:0.1, sg:-1, ch:'operations', src:'Hyperscale datacenter power consumer; weak opposite-sign cost transmission. Non-tradable node (propagates to GOOGL).'},
  {a:'TSMC', b:'ELECTRICITY', v:0.12, sg:-1, ch:'operations', src:'Fabs are extremely power-intensive (TSMC is a top single consumer of Taiwan\'s electricity); power cost/availability is a real but margin-buffered headwind. Weak-to-moderate opposite-sign.'},
  {a:'F', b:'CRUDE', v:0.2, sg:-1, ch:'demand', src:'High oil/gasoline prices dampen demand for ICE/large trucks (Ford\'s profit pool) and raise input/logistics costs; opposite-sign demand transmission.'},
  {a:'GM', b:'CRUDE', v:0.2, sg:-1, ch:'demand', src:'High oil hits demand for GM\'s ICE truck/SUV mix and raises costs; opposite-sign demand transmission.'},
  {a:'TM', b:'CRUDE', v:0.12, sg:-1, ch:'demand', src:'Toyota is more hybrid-weighted, so less oil-sensitive than US truck makers, but high oil still pressures volumes/costs. Opposite-sign, smaller.'},
  {a:'TSLA', b:'CRUDE', v:0.18, sg:1, ch:'demand', src:'SUBSTITUTION angle: high crude/gasoline prices IMPROVE the relative economics of EVs, a demand tailwind for Tesla. Modeled as CONSUMES with POSITIVE sign (sign-flipped vs a normal consumer) to capture the oil->EV substitution. Explicitly noted.'},
  {a:'BYD', b:'CRUDE', v:0.15, sg:1, ch:'demand', src:'Same EV substitution angle: high oil aids EV/PHEV adoption (BYD also sells PHEVs, so slightly weaker pure-EV effect). CONSUMES with POSITIVE sign. Noted.'},
  {a:'CATL', b:'LITHIUM', v:0.25, sg:-1, ch:'operations', src:'World\'s largest battery maker; lithium is a major cell input cost. Note: CATL passes through cost and benefits from volume, so net stock effect is partly offset, hence moderate opposite-sign weight.'},
  {a:'LGES', b:'LITHIUM', v:0.25, sg:-1, ch:'operations', src:'Major battery maker; lithium input-cost exposure, partly passed through. Moderate opposite-sign.'},
  {a:'PANA', b:'LITHIUM', v:0.18, sg:-1, ch:'operations', src:'Battery maker (Tesla supplier) but lithium is a smaller share of diversified Panasonic; opposite-sign, smaller.'},
  {a:'TSLA', b:'LITHIUM', v:0.15, sg:-1, ch:'operations', src:'Lithium is a battery input cost for Tesla\'s vehicles/energy storage; high lithium = margin headwind. Opposite-sign, modest (Tesla buys cells/has supply deals).'},
  {a:'BYD', b:'LITHIUM', v:0.18, sg:-1, ch:'operations', src:'BYD is vertically integrated (makes its own batteries), so lithium price is a direct input cost. Opposite-sign.'},
  {a:'F', b:'RARE_EARTH', v:0.08, sg:-1, ch:'operations', src:'NdFeB permanent magnets are used in EV traction motors; a rare-earth squeeze (esp. China export curbs) is a cost/continuity risk. Small share of cost, weak transmission.'},
  {a:'GM', b:'RARE_EARTH', v:0.08, sg:-1, ch:'operations', src:'EV motor magnets use rare earths (NdPr); rare-earth supply shock is an input/continuity risk. Weak opposite-sign.'},
  {a:'TSLA', b:'RARE_EARTH', v:0.1, sg:-1, ch:'operations', src:'Permanent-magnet motors use rare earths; supply/price shock is a cost/continuity risk (Tesla has moved to cut rare-earth use, so modest). Opposite-sign.'},
  {a:'BYD', b:'RARE_EARTH', v:0.1, sg:-1, ch:'operations', src:'EV motor magnets; rare-earth input/continuity exposure (China-sourced, so closer to supply). Opposite-sign.'}
] AS e
MATCH (c:Company {ticker:e.a}),(n:Commodity {id:e.b})
MERGE (c)-[r:CONSUMES]->(n) SET r.value=e.v, r.sign=e.sg, r.channel=e.ch, r.source=e.src;

// ---------- EXPOSED_TO_THEME (seed-only exposure) ----------
UNWIND [
  {a:'NVDA', b:'AI-capex', v:1, sg:1, ch:'Bellwether of the AI-accelerator capex trade; the stock IS the AI-capex narrative (record $589B 1-day loss on the DeepSeek capex-doubt shock).', src:'public'},
  {a:'AVGO', b:'AI-capex', v:0.9, sg:1, ch:'Custom AI silicon (XPUs) + AI networking for hyperscalers; guided $60-90B AI TAM. Moves tightly with the capex thesis (-17% on DeepSeek, +24% on its own AI guide).', src:'public'},
  {a:'MRVL', b:'AI-capex', v:0.85, sg:1, ch:'Custom AI ASIC / AI-datacenter optics/networking; highest-torque small-cap proxy for hyperscaler silicon spend.', src:'public'},
  {a:'TSMC', b:'AI-capex', v:0.75, sg:1, ch:'Sole leading-edge + CoWoS manufacturer for AI accelerators; AI HPC is the dominant revenue-growth driver, but diversified (mobile/auto) caps the loading below the pure-plays.', src:'public'},
  {a:'SMCI', b:'AI-capex', v:0.85, sg:1, ch:'Highest-beta AI server/rack integrator; revenue is almost entirely AI-datacenter systems. (Idiosyncratic accounting overhang adds non-theme volatility.)', src:'public'},
  {a:'DELL', b:'AI-capex', v:0.55, sg:1, ch:'AI server backlog is the growth/re-rating driver, but a large legacy PC/enterprise base dilutes the AI-capex transmission.', src:'public'},
  {a:'ANET', b:'AI-capex', v:0.7, sg:1, ch:'AI-datacenter Ethernet networking; revenue concentrated in hyperscalers, so the stock trades on AI back-end-network capex.', src:'public'},
  {a:'AMD', b:'AI-capex', v:0.6, sg:1, ch:'MI-series AI accelerators are the swing growth story, but a large non-AI CPU/client/embedded base dilutes the pure capex beta.', src:'public'},
  {a:'VST', b:'AI-power-demand', v:0.85, sg:1, ch:'IPP with nuclear + gas fleet; lead datacenter-power re-rating name (Talen/Constellation-style PPAs), stock moves on AI power-demand headlines.', src:'public'},
  {a:'CEG', b:'AI-power-demand', v:0.9, sg:1, ch:'Largest US nuclear fleet; signed datacenter PPAs (incl. Microsoft/Three Mile Island restart). The flagship AI-power-demand stock.', src:'public'},
  {a:'NRG', b:'AI-power-demand', v:0.6, sg:1, ch:'Independent power / retail; benefits from the AI load-growth and tight-capacity narrative, but more retail/hedged than the nuclear pure-plays.', src:'public'},
  {a:'GEV', b:'AI-power-demand', v:0.75, sg:1, ch:'Gas turbines + grid equipment; order book re-rates on datacenter-driven generation and grid build-out.', src:'public'},
  {a:'ETN', b:'AI-power-demand', v:0.65, sg:1, ch:'Electrical power-management gear for datacenters; AI datacenter electrification is the key growth/multiple driver, diluted by a broad industrial base.', src:'public'},
  {a:'VRT', b:'AI-power-demand', v:0.8, sg:1, ch:'Datacenter thermal/power (cooling, busbar, UPS); a near-pure AI-datacenter capex+power-density play, high transmission.', src:'public'},
  {a:'PWR', b:'AI-power-demand', v:0.6, sg:1, ch:'Electrical infrastructure / transmission EPC; benefits from grid build-out for AI load growth, diluted by broad utility/telecom work.', src:'public'},
  {a:'VST', b:'AI-capex', v:0.4, sg:1, ch:'BEAR-CASE LINK: power-demand thesis is downstream of AI capex; VST sold off in the DeepSeek capex-doubt shock despite no change to current load.', src:'public'},
  {a:'CEG', b:'AI-capex', v:0.4, sg:1, ch:'BEAR-CASE LINK: datacenter-PPA re-rating is contingent on the AI build-out continuing; de-rates if AI capex stalls.', src:'public'},
  {a:'GEV', b:'AI-capex', v:0.35, sg:1, ch:'BEAR-CASE LINK: turbine/grid order-book optimism is tied to sustained AI datacenter spend.', src:'public'},
  {a:'VRT', b:'AI-capex', v:0.45, sg:1, ch:'BEAR-CASE LINK: datacenter thermal/power demand is a direct function of AI capex; falls with the accelerator trade.', src:'public'},
  {a:'SKH', b:'HBM-memory', v:0.95, sg:1, ch:'HBM market-share leader and lead supplier to NVIDIA; the purest HBM-cycle stock (record Q3-24 profit on HBM/AI demand).', src:'public'},
  {a:'MU', b:'HBM-memory', v:0.7, sg:1, ch:'HBM3E ramp is the re-rating driver, but a large commodity DRAM/NAND base ties it to the broader memory cycle, diluting pure-HBM beta.', src:'public'},
  {a:'SMSN', b:'HBM-memory', v:0.55, sg:1, ch:'HBM upside is real but it is the share-loser/laggard in HBM qualification, and a huge diversified franchise (foundry/handset/display) dilutes transmission.', src:'public'},
  {a:'HANMI', b:'HBM-memory', v:0.95, sg:1, ch:'Dominant TC-bonder supplier for HBM stacking; a near-pure HBM-capex equipment proxy — stock is one of the highest-beta HBM plays.', src:'public'},
  {a:'BESI', b:'HBM-memory', v:0.6, sg:1, ch:'Hybrid-bonding leader — the next-gen HBM/advanced-packaging tool optionality drives the multiple; partially diluted by mainstream assembly cyclicality.', src:'public'},
  {a:'NVDA', b:'export-control', v:0.45, sg:-1, ch:'Loses high-end China accelerator revenue with each tightening (H20/A800/H800 restrictions); sign -1, but China is a minority of revenue so loading is moderate.', src:'public'},
  {a:'ASML', b:'export-control', v:0.6, sg:-1, ch:'EUV already barred; DUV-to-China curbs and a large recent China backlog mean each tightening is a direct demand headwind. Sign -1.', src:'public'},
  {a:'AMAT', b:'export-control', v:0.6, sg:-1, ch:'High China WFE revenue share; deposition/etch/CMP tools are squarely in the entity-list/curb scope. Sign -1.', src:'public'},
  {a:'LRCX', b:'export-control', v:0.6, sg:-1, ch:'Etch/deposition tools to Chinese fabs heavily curbed; among the most China-WFE-exposed US equipment names. Sign -1.', src:'public'},
  {a:'KLAC', b:'export-control', v:0.55, sg:-1, ch:'Process-control/metrology tools to China restricted; meaningful China revenue share. Sign -1.', src:'public'},
  {a:'SMIC', b:'export-control', v:0.45, sg:1, ch:'Sign +1 (winner): controls entrench it as the protected, state-subsidized domestic foundry champion via forced import-substitution; partly offset by being cut off from leading-edge tools, hence moderate loading.', src:'public'},
  {a:'BABA', b:'China-tech', v:0.9, sg:1, ch:'Bellwether US-listed China-internet ADR; the lead basket name in China risk-on/off (jumped on Sep-2024 PBOC stimulus).', src:'public'},
  {a:'TENCENT', b:'China-tech', v:0.9, sg:1, ch:'Largest HK-listed China-tech weight; core of the China-tech basket beta.', src:'public'},
  {a:'BIDU', b:'China-tech', v:0.85, sg:1, ch:'US-listed China internet/AI ADR; moves with the basket on China macro/regulatory sentiment.', src:'public'},
  {a:'JD', b:'China-tech', v:0.8, sg:1, ch:'US-listed China e-commerce ADR; high basket co-movement on China risk-on/off.', src:'public'},
  {a:'XIAOMI', b:'China-tech', v:0.75, sg:1, ch:'HK-listed China consumer-tech; trades with the China-tech basket plus its own EV/hardware idiosyncrasies (slightly diluted).', src:'public'},
  {a:'SMIC', b:'China-tech', v:0.7, sg:1, ch:'HK-listed China domestic-chip champion; rallies with the China-tech / chip-self-sufficiency basket.', src:'public'},
  {a:'TSLA', b:'EV-transition', v:0.85, sg:1, ch:'Global pure-play EV bellwether; the stock IS the EV-transition narrative (though increasingly priced on AI/robotaxi optionality too, slightly capping loading).', src:'public'},
  {a:'BYD', b:'EV-transition', v:0.9, sg:1, ch:'World\'s top NEV seller; pure-play beneficiary of EV penetration and the EV price war (overtook Tesla on volume).', src:'public'},
  {a:'NIO', b:'EV-transition', v:0.85, sg:1, ch:'Chinese pure-play EV startup; high-beta to EV demand/penetration and subsidy sentiment.', src:'public'},
  {a:'GM', b:'EV-transition', v:0.4, sg:1, ch:'Legacy OEM: EV transition is volume-positive but margin-dilutive and a minority of the franchise, so transmission is partial and ambiguous (lower loading).', src:'public'},
  {a:'CATL', b:'EV-transition', v:0.85, sg:1, ch:'World\'s largest EV battery maker; directly levered to global EV battery demand.', src:'public'},
  {a:'PANA', b:'EV-transition', v:0.5, sg:1, ch:'Tesla/North-America battery supplier — EV batteries are the growth driver, but a large diversified industrial/appliance base dilutes the EV beta.', src:'public'},
  {a:'ALB', b:'EV-transition', v:0.75, sg:1, ch:'Largest lithium producer; share price tracks EV-battery demand/lithium-price expectations (sign +1 on the EV-demand axis, though oversupply can invert the lithium-price leg).', src:'public'},
  {a:'RXRX', b:'AI-drug-discovery', v:0.85, sg:1, ch:'Pure-play AI drug-discovery platform; stock trades on the AI-in-biology thesis and platform/partnership newsflow.', src:'public'},
  {a:'SDGR', b:'AI-drug-discovery', v:0.8, sg:1, ch:'Computational/physics-based drug-design software + pipeline; core AI-drug-discovery name.', src:'public'},
  {a:'TEM', b:'AI-drug-discovery', v:0.8, sg:1, ch:'AI-driven precision-medicine diagnostics/data; a flagship TechBio/AI-healthcare stock.', src:'public'},
  {a:'ILMN', b:'AI-drug-discovery', v:0.3, sg:1, ch:'Genomics-sequencing incumbent; catches AI-in-biology sentiment but is a mature, fundamentals-driven tools company, so low thematic transmission.', src:'public'},
  {a:'RXRX', b:'AI-capex', v:0.25, sg:1, ch:'Small AI-sentiment beta only: catches AI risk-on/off, NOT hyperscaler accelerator spend (no fake NVDA-supply edge).', src:'public'},
  {a:'SDGR', b:'AI-capex', v:0.2, sg:1, ch:'Small AI-sentiment beta only; not levered to datacenter capex.', src:'public'},
  {a:'TEM', b:'AI-capex', v:0.25, sg:1, ch:'Small AI-sentiment beta only; \'AI\' label drives some co-movement with the broad AI trade, not capex fundamentals.', src:'public'}
] AS e
MATCH (c:Company {ticker:e.a}),(n:Theme {id:e.b})
MERGE (c)-[r:EXPOSED_TO_THEME]->(n) SET r.value=e.v, r.sign=e.sg, r.channel=e.ch, r.source=e.src;

// ---------- CONSTRAINS (seed-only exposure) ----------
UNWIND [
  {a:'cond_us_china_chip_controls', b:'NVDA', v:0.6, sg:-1, ch:'policy', src:'BIS 2022-10-07 rule; CNBC 2023-10-17 (A800/H800 ban); company filings on China revenue at risk'},
  {a:'cond_us_china_chip_controls', b:'AMD', v:0.4, sg:-1, ch:'policy', src:'BIS rule names MI/AI accelerators; AMD flagged China datacenter-GPU sales restricted'},
  {a:'cond_us_china_chip_controls', b:'ASML', v:0.55, sg:-1, ch:'policy', src:'EUV banned to China; advanced-DUV (NXT:2000i+) restricted under US+NL controls; China was a large bookings share'},
  {a:'cond_us_china_chip_controls', b:'AMAT', v:0.5, sg:-1, ch:'policy', src:'BIS WFE controls curb deposition/etch tool exports to advanced Chinese fabs; China a major revenue region'},
  {a:'cond_us_china_chip_controls', b:'LRCX', v:0.5, sg:-1, ch:'policy', src:'Lam etch/deposition equipment exports to China curbed; large China revenue exposure'},
  {a:'cond_us_china_chip_controls', b:'KLAC', v:0.45, sg:-1, ch:'policy', src:'KLA process-control/metrology tools restricted; US-person support to Chinese fabs limited'},
  {a:'cond_us_china_chip_controls', b:'8035.T', v:0.4, sg:-1, ch:'policy', src:'Tokyo Electron WFE exports to China curbed under aligned Japan controls (Jul-2023); large China sales mix'},
  {a:'cond_us_china_chip_controls', b:'SMIC', v:0.4, sg:1, ch:'policy', src:'Reuters/Fortune: SMIC benefits as China customers forced to domestic foundries; self-sufficiency bid offsets tool-access constraint in stock reaction'},
  {a:'cond_us_china_chip_controls', b:'HUAHONG', v:0.35, sg:1, ch:'policy', src:'Hua Hong is a mature-node localization beneficiary of forced China self-sufficiency under the controls'},
  {a:'cond_us_china_tariffs', b:'AAPL', v:0.4, sg:-1, ch:'policy', src:'China-concentrated assembly + China end-market revenue; Section 301 tariff escalation is a recurring overhang'},
  {a:'cond_us_china_tariffs', b:'TSLA', v:0.3, sg:-1, ch:'policy', src:'Shanghai Gigafactory output + China demand exposed to retaliatory tariffs/trade-war risk'},
  {a:'cond_us_china_tariffs', b:'BABA', v:0.3, sg:-1, ch:'policy', src:'US-listed China exporter/internet name pressured by US-China trade escalation and tariff-driven China-risk sentiment'}
] AS e
MATCH (cond:Condition {id:e.a}),(c:Company {ticker:e.b})
MERGE (cond)-[r:CONSTRAINS]->(c) SET r.value=e.v, r.sign=e.sg, r.channel=e.ch, r.source=e.src;

// =======================================================================
// NEWS EVENTS  (AFFECTS company hits; macro seeds -> country/commodity/theme/condition)
// =======================================================================

// evt_tsmc_quake_2024  (2024-04-03, supply_chain_disruption, scope=company)
MERGE (e:NewsEvent {id:'evt_tsmc_quake_2024'})
  SET e.headline = 'Magnitude 7.4 earthquake hits Taiwan; TSMC halts production at multiple fabs',
      e.source = 'Reuters', e.url = 'https://www.reuters.com/world/asia-pacific/taiwan-earthquake-2024-04-03/',
      e.sentiment = -0.85, e.category = 'supply_chain_disruption', e.scope = 'company',
      e.date = '2024-04-03', e.ts = datetime('2024-04-03T00:00:00Z');
WITH 1 AS _
UNWIND [
  {t:'TSMC', d:0.85, sg:-1, why:'Fabs evacuated and wafers in process scrapped; output disrupted'}
] AS h
MATCH (e:NewsEvent {id:'evt_tsmc_quake_2024'}),(c:Company {ticker:h.t})
MERGE (e)-[a:AFFECTS]->(c) SET a.directImpact = h.d, a.sign = h.sg, a.why = h.why;

// evt_nvda_ai_surge_2024  (2024-02-22, demand_surge, scope=company)
MERGE (e:NewsEvent {id:'evt_nvda_ai_surge_2024'})
  SET e.headline = 'NVIDIA posts record datacenter revenue as AI demand surges; shares jump',
      e.source = 'Bloomberg', e.url = 'https://www.bloomberg.com/news/articles/nvidia-q4-fy24-earnings-2024-02-21',
      e.sentiment = 0.8, e.category = 'demand_surge', e.scope = 'company',
      e.date = '2024-02-22', e.ts = datetime('2024-02-22T00:00:00Z');
WITH 1 AS _
UNWIND [
  {t:'NVDA', d:0.8, sg:1, why:'Datacenter revenue blowout and strong guidance after Feb 21 close'}
] AS h
MATCH (e:NewsEvent {id:'evt_nvda_ai_surge_2024'}),(c:Company {ticker:h.t})
MERGE (e)-[a:AFFECTS]->(c) SET a.directImpact = h.d, a.sign = h.sg, a.why = h.why;

// evt_chip_export_curbs_2024  (2024-12-02, regulatory, scope=company)
MERGE (e:NewsEvent {id:'evt_chip_export_curbs_2024'})
  SET e.headline = 'US tightens export controls on advanced chips and equipment to China',
      e.source = 'WSJ', e.url = 'https://www.wsj.com/tech/us-china-chip-export-controls-december-2024',
      e.sentiment = -0.49, e.category = 'regulatory', e.scope = 'company',
      e.date = '2024-12-02', e.ts = datetime('2024-12-02T00:00:00Z');
WITH 1 AS _
UNWIND [
  {t:'NVDA', d:0.55, sg:-1, why:'Tighter limits on advanced AI accelerator sales to China'},
  {t:'ASML', d:0.5, sg:-1, why:'Lithography tool shipments to Chinese fabs further restricted'},
  {t:'AMAT', d:0.45, sg:-1, why:'Deposition/etch equipment exports curbed'},
  {t:'LRCX', d:0.45, sg:-1, why:'Etch equipment exports to China curbed'}
] AS h
MATCH (e:NewsEvent {id:'evt_chip_export_curbs_2024'}),(c:Company {ticker:h.t})
MERGE (e)-[a:AFFECTS]->(c) SET a.directImpact = h.d, a.sign = h.sg, a.why = h.why;

// evt_tesla_q1_miss_2024  (2024-04-02, earnings, scope=company)
MERGE (e:NewsEvent {id:'evt_tesla_q1_miss_2024'})
  SET e.headline = 'Tesla Q1 deliveries fall well short of estimates',
      e.source = 'CNBC', e.url = 'https://www.cnbc.com/2024/04/02/tesla-tsla-q1-2024-vehicle-delivery-and-production-numbers.html',
      e.sentiment = -0.6, e.category = 'earnings', e.scope = 'company',
      e.date = '2024-04-02', e.ts = datetime('2024-04-02T00:00:00Z');
WITH 1 AS _
UNWIND [
  {t:'TSLA', d:0.6, sg:-1, why:'First YoY delivery decline in years; demand and price-cut worries'}
] AS h
MATCH (e:NewsEvent {id:'evt_tesla_q1_miss_2024'}),(c:Company {ticker:h.t})
MERGE (e)-[a:AFFECTS]->(c) SET a.directImpact = h.d, a.sign = h.sg, a.why = h.why;

// evt_byd_overtakes_tesla_2024  (2024-01-02, sector, scope=company)
MERGE (e:NewsEvent {id:'evt_byd_overtakes_tesla_2024'})
  SET e.headline = 'BYD overtakes Tesla as the world\'s top EV seller in Q4',
      e.source = 'Financial Times', e.url = 'https://www.ft.com/content/byd-tesla-ev-sales-q4-2023',
      e.sentiment = 0.07, e.category = 'sector', e.scope = 'company',
      e.date = '2024-01-02', e.ts = datetime('2024-01-02T00:00:00Z');
WITH 1 AS _
UNWIND [
  {t:'BYD', d:0.6, sg:1, why:'Record quarterly BEV deliveries; took the global volume crown'},
  {t:'TSLA', d:0.45, sg:-1, why:'Lost the top-seller title; intensifying EV price war'}
] AS h
MATCH (e:NewsEvent {id:'evt_byd_overtakes_tesla_2024'}),(c:Company {ticker:h.t})
MERGE (e)-[a:AFFECTS]->(c) SET a.directImpact = h.d, a.sign = h.sg, a.why = h.why;

// evt_asml_guidance_cut_2024  (2024-10-15, earnings, scope=company)
MERGE (e:NewsEvent {id:'evt_asml_guidance_cut_2024'})
  SET e.headline = 'ASML shares plunge after orders miss and outlook cut (early release)',
      e.source = 'Reuters', e.url = 'https://www.reuters.com/technology/asml-q3-2024-results-2024-10-15/',
      e.sentiment = -0.75, e.category = 'earnings', e.scope = 'company',
      e.date = '2024-10-15', e.ts = datetime('2024-10-15T00:00:00Z');
WITH 1 AS _
UNWIND [
  {t:'ASML', d:0.75, sg:-1, why:'Bookings far below consensus; 2025 sales guidance cut'}
] AS h
MATCH (e:NewsEvent {id:'evt_asml_guidance_cut_2024'}),(c:Company {ticker:h.t})
MERGE (e)-[a:AFFECTS]->(c) SET a.directImpact = h.d, a.sign = h.sg, a.why = h.why;

// evt_intel_q2_miss_2024  (2024-08-02, earnings, scope=company)
MERGE (e:NewsEvent {id:'evt_intel_q2_miss_2024'})
  SET e.headline = 'Intel plunges on weak guidance, dividend suspension and layoffs',
      e.source = 'Bloomberg', e.url = 'https://www.bloomberg.com/news/articles/intel-q2-2024-results-2024-08-01',
      e.sentiment = -0.7, e.category = 'earnings', e.scope = 'company',
      e.date = '2024-08-02', e.ts = datetime('2024-08-02T00:00:00Z');
WITH 1 AS _
UNWIND [
  {t:'INTC', d:0.7, sg:-1, why:'Guidance cut, dividend suspended, ~15% workforce reduction'}
] AS h
MATCH (e:NewsEvent {id:'evt_intel_q2_miss_2024'}),(c:Company {ticker:h.t})
MERGE (e)-[a:AFFECTS]->(c) SET a.directImpact = h.d, a.sign = h.sg, a.why = h.why;

// evt_micron_beat_2024  (2024-09-26, earnings, scope=company)
MERGE (e:NewsEvent {id:'evt_micron_beat_2024'})
  SET e.headline = 'Micron jumps on AI-driven memory demand and upbeat guidance',
      e.source = 'Reuters', e.url = 'https://www.reuters.com/technology/micron-fq4-2024-results-2024-09-25/',
      e.sentiment = 0.65, e.category = 'earnings', e.scope = 'company',
      e.date = '2024-09-26', e.ts = datetime('2024-09-26T00:00:00Z');
WITH 1 AS _
UNWIND [
  {t:'MU', d:0.65, sg:1, why:'HBM/DRAM strength on AI; guidance above estimates after Sep 25 close'}
] AS h
MATCH (e:NewsEvent {id:'evt_micron_beat_2024'}),(c:Company {ticker:h.t})
MERGE (e)-[a:AFFECTS]->(c) SET a.directImpact = h.d, a.sign = h.sg, a.why = h.why;

// evt_google_antitrust_2024  (2024-08-05, regulatory, scope=company)
MERGE (e:NewsEvent {id:'evt_google_antitrust_2024'})
  SET e.headline = 'US judge rules Google illegally monopolized online search',
      e.source = 'Reuters', e.url = 'https://www.reuters.com/legal/google-antitrust-search-ruling-2024-08-05/',
      e.sentiment = -0.6, e.category = 'regulatory', e.scope = 'company',
      e.date = '2024-08-05', e.ts = datetime('2024-08-05T00:00:00Z');
WITH 1 AS _
UNWIND [
  {t:'GOOGL', d:0.6, sg:-1, why:'Landmark monopoly ruling; remedies and ad/search risk overhang'}
] AS h
MATCH (e:NewsEvent {id:'evt_google_antitrust_2024'}),(c:Company {ticker:h.t})
MERGE (e)-[a:AFFECTS]->(c) SET a.directImpact = h.d, a.sign = h.sg, a.why = h.why;

// evt_samsung_strike_2024  (2024-07-08, supply_chain_disruption, scope=company)
MERGE (e:NewsEvent {id:'evt_samsung_strike_2024'})
  SET e.headline = 'Samsung Electronics union stages first-ever strike',
      e.source = 'Reuters', e.url = 'https://www.reuters.com/technology/samsung-electronics-union-strike-2024-07-08/',
      e.sentiment = -0.5, e.category = 'supply_chain_disruption', e.scope = 'company',
      e.date = '2024-07-08', e.ts = datetime('2024-07-08T00:00:00Z');
WITH 1 AS _
UNWIND [
  {t:'SMSN', d:0.5, sg:-1, why:'Production/operational risk from indefinite walkout at chip lines'}
] AS h
MATCH (e:NewsEvent {id:'evt_samsung_strike_2024'}),(c:Company {ticker:h.t})
MERGE (e)-[a:AFFECTS]->(c) SET a.directImpact = h.d, a.sign = h.sg, a.why = h.why;

// evt_apple_intelligence_wwdc_2024  (2024-06-11, demand_surge, scope=company)
MERGE (e:NewsEvent {id:'evt_apple_intelligence_wwdc_2024'})
  SET e.headline = 'Apple unveils Apple Intelligence at WWDC; shares hit record high',
      e.source = 'CNBC', e.url = 'https://www.cnbc.com/2024/06/11/apple-stock-record-high-after-wwdc-apple-intelligence.html',
      e.sentiment = 0.6, e.category = 'demand_surge', e.scope = 'company',
      e.date = '2024-06-11', e.ts = datetime('2024-06-11T00:00:00Z');
WITH 1 AS _
UNWIND [
  {t:'AAPL', d:0.6, sg:1, why:'AI features seen driving an iPhone upgrade super-cycle'}
] AS h
MATCH (e:NewsEvent {id:'evt_apple_intelligence_wwdc_2024'}),(c:Company {ticker:h.t})
MERGE (e)-[a:AFFECTS]->(c) SET a.directImpact = h.d, a.sign = h.sg, a.why = h.why;

// evt_nvda_blackwell_delay_2024  (2024-08-05, supply_chain_disruption, scope=company)
MERGE (e:NewsEvent {id:'evt_nvda_blackwell_delay_2024'})
  SET e.headline = 'Report: NVIDIA\'s Blackwell AI GPUs delayed by a design flaw',
      e.source = 'The Information', e.url = 'https://www.theinformation.com/articles/nvidia-blackwell-delay-2024',
      e.sentiment = -0.5, e.category = 'supply_chain_disruption', e.scope = 'company',
      e.date = '2024-08-05', e.ts = datetime('2024-08-05T00:00:00Z');
WITH 1 AS _
UNWIND [
  {t:'NVDA', d:0.5, sg:-1, why:'Packaging design flaw reportedly pushes Blackwell ramp by months'}
] AS h
MATCH (e:NewsEvent {id:'evt_nvda_blackwell_delay_2024'}),(c:Company {ticker:h.t})
MERGE (e)-[a:AFFECTS]->(c) SET a.directImpact = h.d, a.sign = h.sg, a.why = h.why;

// evt_tsmc_earnings_beat_2024  (2024-07-18, earnings, scope=company)
MERGE (e:NewsEvent {id:'evt_tsmc_earnings_beat_2024'})
  SET e.headline = 'TSMC posts record profit on AI chip demand and raises outlook',
      e.source = 'Reuters', e.url = 'https://www.reuters.com/technology/tsmc-q2-2024-results-2024-07-18/',
      e.sentiment = 0.7, e.category = 'earnings', e.scope = 'company',
      e.date = '2024-07-18', e.ts = datetime('2024-07-18T00:00:00Z');
WITH 1 AS _
UNWIND [
  {t:'TSMC', d:0.7, sg:1, why:'Profit beat and raised full-year revenue guidance on AI demand'}
] AS h
MATCH (e:NewsEvent {id:'evt_tsmc_earnings_beat_2024'}),(c:Company {ticker:h.t})
MERGE (e)-[a:AFFECTS]->(c) SET a.directImpact = h.d, a.sign = h.sg, a.why = h.why;

// evt_visa_doj_antitrust_2024  (2024-09-24, regulatory, scope=company)
MERGE (e:NewsEvent {id:'evt_visa_doj_antitrust_2024'})
  SET e.headline = 'US DOJ sues Visa over alleged debit-network monopoly',
      e.source = 'Reuters', e.url = 'https://www.reuters.com/legal/doj-visa-debit-antitrust-lawsuit-2024-09-24/',
      e.sentiment = -0.5, e.category = 'regulatory', e.scope = 'company',
      e.date = '2024-09-24', e.ts = datetime('2024-09-24T00:00:00Z');
WITH 1 AS _
UNWIND [
  {t:'V', d:0.5, sg:-1, why:'Antitrust suit targets debit fees and exclusionary practices'}
] AS h
MATCH (e:NewsEvent {id:'evt_visa_doj_antitrust_2024'}),(c:Company {ticker:h.t})
MERGE (e)-[a:AFFECTS]->(c) SET a.directImpact = h.d, a.sign = h.sg, a.why = h.why;

// evt_fed_hawkish_dec_2024  (2024-12-18, macro, scope=company)
MERGE (e:NewsEvent {id:'evt_fed_hawkish_dec_2024'})
  SET e.headline = 'Fed cuts but signals fewer 2025 cuts; stocks tumble broadly',
      e.source = 'Bloomberg', e.url = 'https://www.bloomberg.com/news/articles/fomc-december-2024-decision',
      e.sentiment = -0.38, e.category = 'macro', e.scope = 'company',
      e.date = '2024-12-18', e.ts = datetime('2024-12-18T00:00:00Z');
WITH 1 AS _
UNWIND [
  {t:'NVDA', d:0.4, sg:-1, why:'High-multiple growth names sold off on higher-for-longer rates'},
  {t:'JPM', d:0.4, sg:-1, why:'Broad risk-off; rate-path repricing hit financials'},
  {t:'AAPL', d:0.35, sg:-1, why:'Mega-cap drawdown in a market-wide de-rating'}
] AS h
MATCH (e:NewsEvent {id:'evt_fed_hawkish_dec_2024'}),(c:Company {ticker:h.t})
MERGE (e)-[a:AFFECTS]->(c) SET a.directImpact = h.d, a.sign = h.sg, a.why = h.why;

// evt_china_stimulus_2024  (2024-09-24, macro, scope=company)
MERGE (e:NewsEvent {id:'evt_china_stimulus_2024'})
  SET e.headline = 'PBOC unveils sweeping monetary stimulus (rate and RRR cuts, property and equity support); Chinese equities and US-listed China names rally',
      e.source = 'Bloomberg', e.url = 'https://www.bloomberg.com/news/articles/2024-09-24/china-cuts-key-rate-rrr-in-broad-stimulus-push',
      e.sentiment = 0.5, e.category = 'macro', e.scope = 'company',
      e.date = '2024-09-24', e.ts = datetime('2024-09-24T00:00:00Z');
WITH 1 AS _
UNWIND [
  {t:'BABA', d:0.65, sg:1, why:'US-listed China internet bellwether jumped on the stimulus-driven China re-rating'},
  {t:'BYD', d:0.45, sg:1, why:'Hong Kong-listed China consumer/auto name lifted by broad China risk-on'},
  {t:'CATL', d:0.4, sg:1, why:'A-share battery leader rallied with the onshore CSI 300 stimulus surge'}
] AS h
MATCH (e:NewsEvent {id:'evt_china_stimulus_2024'}),(c:Company {ticker:h.t})
MERGE (e)-[a:AFFECTS]->(c) SET a.directImpact = h.d, a.sign = h.sg, a.why = h.why;

// evt_yen_carry_unwind_2024  (2024-08-05, macro, scope=company)
MERGE (e:NewsEvent {id:'evt_yen_carry_unwind_2024'})
  SET e.headline = 'Global risk-off as yen carry trade unwinds after BoJ hike and weak US jobs; Nikkei plunges ~12%, Nasdaq sells off hard',
      e.source = 'CNBC', e.url = 'https://www.cnbc.com/2024/08/05/carry-trades-a-major-unwinding-is-underway-amid-a-stock-sell-off.html',
      e.sentiment = -0.53, e.category = 'macro', e.scope = 'company',
      e.date = '2024-08-05', e.ts = datetime('2024-08-05T00:00:00Z');
WITH 1 AS _
UNWIND [
  {t:'NVDA', d:0.55, sg:-1, why:'High-beta AI leader fell hard in the broad megacap-tech selloff'},
  {t:'AAPL', d:0.4, sg:-1, why:'Dropped amid risk-off plus Berkshire stake-cut news'},
  {t:'SMCI', d:0.6, sg:-1, why:'Highest-beta AI hardware name fell sharply in the deleveraging'},
  {t:'PANA', d:0.55, sg:-1, why:'Japanese name slammed as Nikkei 225 fell ~12% on the yen surge'}
] AS h
MATCH (e:NewsEvent {id:'evt_yen_carry_unwind_2024'}),(c:Company {ticker:h.t})
MERGE (e)-[a:AFFECTS]->(c) SET a.directImpact = h.d, a.sign = h.sg, a.why = h.why;

// evt_deepseek_selloff_2025  (2025-01-27, sector, scope=macro)
MERGE (e:NewsEvent {id:'evt_deepseek_selloff_2025'})
  SET e.headline = 'China\'s DeepSeek low-cost AI model triggers record tech rout; NVIDIA sheds ~$589B, worst single-day market-cap loss in history',
      e.source = 'Bloomberg', e.url = 'https://www.bloomberg.com/news/articles/2025-01-27/asml-sinks-as-china-ai-startup-triggers-panic-in-tech-stocks',
      e.sentiment = -0.8, e.category = 'sector', e.scope = 'macro',
      e.cv_operations = 0, e.cv_demand = 0.2, e.cv_currency = 0, e.cv_policy = 0,
      e.date = '2025-01-27', e.ts = datetime('2025-01-27T00:00:00Z');
WITH 1 AS _
MATCH (e:NewsEvent {id:'evt_deepseek_selloff_2025'}),(n:Theme {id:'AI-capex'})
MERGE (e)-[r:AFFECTS_THEME]->(n) SET r.severity = 0.8, r.sign = -1, r.why = 'Cheap-compute (DeepSeek R1) shock undercuts the high-AI-capex thesis; seeds every AI-capex-loaded name negative by loading. Re-wired as a macro/theme shock so reach is earned by theme membership, not LLM memory.';

// evt_broadcom_ai_beat_2024  (2024-12-13, earnings, scope=company)
MERGE (e:NewsEvent {id:'evt_broadcom_ai_beat_2024'})
  SET e.headline = 'Broadcom guides to a $60-90B AI chip opportunity by 2027 and signs new custom-AI customers; stock rockets ~24% to a $1T market cap',
      e.source = 'CNBC', e.url = 'https://www.cnbc.com/2024/12/13/broadcom-stock-jumps-21percent-pushing-company-past-1-trillion-market-cap-for-the-first-time.html',
      e.sentiment = 0.65, e.category = 'earnings', e.scope = 'company',
      e.date = '2024-12-13', e.ts = datetime('2024-12-13T00:00:00Z');
WITH 1 AS _
UNWIND [
  {t:'AVGO', d:0.85, sg:1, why:'Surged ~24% on a massive AI custom-silicon TAM and new hyperscaler customers'},
  {t:'MRVL', d:0.45, sg:1, why:'Custom-AI-silicon peer rallied in sympathy on the AVGO readthrough'}
] AS h
MATCH (e:NewsEvent {id:'evt_broadcom_ai_beat_2024'}),(c:Company {ticker:h.t})
MERGE (e)-[a:AFFECTS]->(c) SET a.directImpact = h.d, a.sign = h.sg, a.why = h.why;

// evt_smci_auditor_resign_2024  (2024-10-30, regulatory, scope=company)
MERGE (e:NewsEvent {id:'evt_smci_auditor_resign_2024'})
  SET e.headline = 'Super Micro plunges after auditor Ernst & Young resigns citing inability to rely on management representations',
      e.source = 'CNBC', e.url = 'https://www.cnbc.com/2024/10/30/super-micro-auditor-resigns-after-raising-concerns-months-earlier.html',
      e.sentiment = -0.85, e.category = 'regulatory', e.scope = 'company',
      e.date = '2024-10-30', e.ts = datetime('2024-10-30T00:00:00Z');
WITH 1 AS _
UNWIND [
  {t:'SMCI', d:0.85, sg:-1, why:'Crashed ~32% on the auditor-resignation disclosure and escalating accounting/governance crisis'}
] AS h
MATCH (e:NewsEvent {id:'evt_smci_auditor_resign_2024'}),(c:Company {ticker:h.t})
MERGE (e)-[a:AFFECTS]->(c) SET a.directImpact = h.d, a.sign = h.sg, a.why = h.why;

// evt_skhynix_record_q3_2024  (2024-10-24, earnings, scope=company)
MERGE (e:NewsEvent {id:'evt_skhynix_record_q3_2024'})
  SET e.headline = 'SK hynix posts record Q3 profit on explosive HBM/AI-memory demand; shares jump to a record',
      e.source = 'The Korea Herald', e.url = 'https://www.koreaherald.com/article/10604199',
      e.sentiment = 0.47, e.category = 'earnings', e.scope = 'company',
      e.date = '2024-10-24', e.ts = datetime('2024-10-24T00:00:00Z');
WITH 1 AS _
UNWIND [
  {t:'SKH', d:0.65, sg:1, why:'Record operating profit (W7.03tn, 40% margin) on HBM/AI demand; stock rose to a record'},
  {t:'SMSN', d:0.3, sg:1, why:'Korean memory peer lifted modestly by the bullish HBM/DRAM readthrough'}
] AS h
MATCH (e:NewsEvent {id:'evt_skhynix_record_q3_2024'}),(c:Company {ticker:h.t})
MERGE (e)-[a:AFFECTS]->(c) SET a.directImpact = h.d, a.sign = h.sg, a.why = h.why;

// evt_marvell_ai_beat_2024  (2024-12-04, earnings, scope=company)
MERGE (e:NewsEvent {id:'evt_marvell_ai_beat_2024'})
  SET e.headline = 'Marvell beats on AI-driven data-center revenue, raises outlook and expands a multi-year AWS custom-silicon partnership; shares hit a record high',
      e.source = 'Bloomberg', e.url = 'https://www.bloomberg.com/news/articles/2024-12-03/marvell-rallies-after-demand-for-ai-computing-bolsters-outlook',
      e.sentiment = 0.75, e.category = 'earnings', e.scope = 'company',
      e.date = '2024-12-04', e.ts = datetime('2024-12-04T00:00:00Z');
WITH 1 AS _
UNWIND [
  {t:'MRVL', d:0.75, sg:1, why:'Jumped ~23% to an all-time high on AI custom-silicon strength and the expanded AWS deal'}
] AS h
MATCH (e:NewsEvent {id:'evt_marvell_ai_beat_2024'}),(c:Company {ticker:h.t})
MERGE (e)-[a:AFFECTS]->(c) SET a.directImpact = h.d, a.sign = h.sg, a.why = h.why;

// evt_apple_iphone16_demand_2024  (2024-09-16, earnings, scope=company)
MERGE (e:NewsEvent {id:'evt_apple_iphone16_demand_2024'})
  SET e.headline = 'Apple slides as analysts flag weak early iPhone 16 demand with Apple Intelligence absent at launch',
      e.source = 'CNBC', e.url = 'https://www.cnbc.com/2024/09/16/apple-shares-slide-on-lower-than-expected-iphone-16-demand-analysts.html',
      e.sentiment = -0.45, e.category = 'earnings', e.scope = 'company',
      e.date = '2024-09-16', e.ts = datetime('2024-09-16T00:00:00Z');
WITH 1 AS _
UNWIND [
  {t:'AAPL', d:0.45, sg:-1, why:'Fell ~2.8% on reports of soft iPhone 16 first-weekend/pre-order demand (Kuo: -12% y/y; Barclays/Citi corroborate)'}
] AS h
MATCH (e:NewsEvent {id:'evt_apple_iphone16_demand_2024'}),(c:Company {ticker:h.t})
MERGE (e)-[a:AFFECTS]->(c) SET a.directImpact = h.d, a.sign = h.sg, a.why = h.why;

// evt_nvda_gtc_blackwell_2024  (2024-03-19, sector, scope=company)
MERGE (e:NewsEvent {id:'evt_nvda_gtc_blackwell_2024'})
  SET e.headline = 'NVIDIA launches the Blackwell GPU platform at GTC 2024',
      e.source = 'CNBC', e.url = 'https://www.cnbc.com/2024/03/19/nvidia-stock-dips-after-company-unveils-latest-ai-chips.html',
      e.sentiment = 0.22, e.category = 'sector', e.scope = 'company',
      e.date = '2024-03-19', e.ts = datetime('2024-03-19T00:00:00Z');
WITH 1 AS _
UNWIND [
  {t:'NVDA', d:0.25, sg:1, why:'Flagship next-gen AI GPU launch; reaction muted \'sell-the-news\' -- NVDA closed up ~1% the session after the keynote'},
  {t:'TSMC', d:0.2, sg:1, why:'Sole leading-edge/CoWoS manufacturer of Blackwell; positive readthrough'},
  {t:'SKH', d:0.2, sg:1, why:'Primary HBM supplier for Blackwell; positive demand readthrough'}
] AS h
MATCH (e:NewsEvent {id:'evt_nvda_gtc_blackwell_2024'}),(c:Company {ticker:h.t})
MERGE (e)-[a:AFFECTS]->(c) SET a.directImpact = h.d, a.sign = h.sg, a.why = h.why;

// evt_taiwan_strait_scare_2022  (2022-08-01, geopolitical, scope=country)
MERGE (e:NewsEvent {id:'evt_taiwan_strait_scare_2022'})
  SET e.headline = 'China threatens \'strong countermeasures\' over imminent Pelosi Taiwan visit; chip stocks and TAIEX slide on Taiwan-Strait conflict fears',
      e.source = 'Bloomberg', e.url = 'https://www.bloomberg.com/news/articles/2022-08-02/taiwan-stocks-decline-as-us-china-tensions-sap-risk-appetite',
      e.sentiment = -0.37, e.category = 'geopolitical', e.scope = 'country',
      e.cv_operations = 0.75, e.cv_demand = 0.1, e.cv_currency = 0.1, e.cv_policy = 0.05,
      e.date = '2022-08-01', e.ts = datetime('2022-08-01T00:00:00Z');
WITH 1 AS _
UNWIND [
  {t:'TSMC', d:0.45, sg:-1, why:'World\'s critical leading-edge fabs concentrated in Taiwan; fell ~2.4-3% on Taiwan-Strait conflict/blockade fear'},
  {t:'FOXCONN', d:0.4, sg:-1, why:'Taiwan-domiciled assembly giant directly exposed to Taiwan operations/territorial risk'},
  {t:'NANYA', d:0.4, sg:-1, why:'Taiwan-based DRAM maker hit by island operations-risk repricing'},
  {t:'NVDA', d:0.25, sg:-1, why:'Single-source dependence on TSMC Taiwan fabs; supply-continuity fear read through to fabless leaders'},
  {t:'AMD', d:0.2, sg:-1, why:'Also fully reliant on TSMC Taiwan capacity; contagion via shared single-point-of-failure'}
] AS h
MATCH (e:NewsEvent {id:'evt_taiwan_strait_scare_2022'}),(c:Company {ticker:h.t})
MERGE (e)-[a:AFFECTS]->(c) SET a.directImpact = h.d, a.sign = h.sg, a.why = h.why;
WITH 1 AS _
MATCH (e:NewsEvent {id:'evt_taiwan_strait_scare_2022'}),(n:Country {code:'TW'})
MERGE (e)-[r:HITS_COUNTRY]->(n) SET r.severity = 0.5, r.sign = -1, r.why = 'Conflict/blockade scare raises Taiwan operations risk; TAIEX fell >2% and TSMC ~2.4-3% as Pelosi visit and China\'s threatened military response loomed. Operations-dominant: hits names with Taiwan fabs/assembly. (Honest note: the Aug-4/5 live-fire drills were actually shrugged off and TAIEX rebounded +2.3%; 2022-08-01 is the genuine down reaction day for the scare.)';

// evt_chip_controls_tighten_2023  (2023-10-17, election_policy, scope=policy)
MERGE (e:NewsEvent {id:'evt_chip_controls_tighten_2023'})
  SET e.headline = 'US tightens China chip export controls, banning Nvidia A800/H800 and more AI/WFE exports to close 2022-rule loopholes',
      e.source = 'CNBC', e.url = 'https://www.cnbc.com/2023/10/17/us-bans-export-of-more-ai-chips-including-nvidia-h800-to-china.html',
      e.sentiment = -0.25, e.category = 'election_policy', e.scope = 'policy',
      e.cv_operations = 0.05, e.cv_demand = 0.15, e.cv_currency = 0, e.cv_policy = 0.8,
      e.date = '2023-10-17', e.ts = datetime('2023-10-17T00:00:00Z');
WITH 1 AS _
UNWIND [
  {t:'NVDA', d:0.4, sg:-1, why:'A800/H800 China workaround SKUs banned; near-term China datacenter-GPU revenue cut off'},
  {t:'AMD', d:0.3, sg:-1, why:'MI-series China AI sales restricted under the broadened thresholds'},
  {t:'SMIC', d:0.25, sg:1, why:'Chinese customers further forced toward domestic foundries; self-sufficiency bid'}
] AS h
MATCH (e:NewsEvent {id:'evt_chip_controls_tighten_2023'}),(c:Company {ticker:h.t})
MERGE (e)-[a:AFFECTS]->(c) SET a.directImpact = h.d, a.sign = h.sg, a.why = h.why;
WITH 1 AS _
MATCH (e:NewsEvent {id:'evt_chip_controls_tighten_2023'}),(n:Condition {id:'cond_us_china_chip_controls'})
MERGE (e)-[r:TIGHTENS]->(n) SET r.severity = 0.55, r.sign = -1, r.why = 'BIS update bans A800/H800/L40/RTX4090-class AI chips and broadens WFE curbs; tightening seeds every CONSTRAINS target with its sign (US/EU/JP chip+WFE exporters down, Chinese domestic foundries up via forced localization)';

// evt_us_election_trump_2024  (2024-11-06, election_policy, scope=policy)
MERGE (e:NewsEvent {id:'evt_us_election_trump_2024'})
  SET e.headline = 'Trump wins 2024 US election; stocks rally on tax/deregulation hopes while tariff and China-trade-war fears hit China-exposed names',
      e.source = 'Bloomberg', e.url = 'https://www.bloomberg.com/news/articles/2024-11-06/stock-market-today-trump-trade-dollar-surges',
      e.sentiment = 0.04, e.category = 'election_policy', e.scope = 'policy',
      e.cv_operations = 0.05, e.cv_demand = 0.1, e.cv_currency = 0.35, e.cv_policy = 0.5,
      e.date = '2024-11-06', e.ts = datetime('2024-11-06T00:00:00Z');
WITH 1 AS _
UNWIND [
  {t:'TSLA', d:0.6, sg:1, why:'Musk-Trump alignment + EV/regulatory tailwind hopes; Tesla surged ~15% the day after the election'},
  {t:'BABA', d:0.4, sg:-1, why:'US-listed China name fell on renewed tariff / trade-war threat under the new administration'},
  {t:'JPM', d:0.35, sg:1, why:'Banks rallied on deregulation and steeper-curve / stronger-dollar reflation trade'}
] AS h
MATCH (e:NewsEvent {id:'evt_us_election_trump_2024'}),(c:Company {ticker:h.t})
MERGE (e)-[a:AFFECTS]->(c) SET a.directImpact = h.d, a.sign = h.sg, a.why = h.why;
WITH 1 AS _
MATCH (e:NewsEvent {id:'evt_us_election_trump_2024'}),(n:Condition {id:'cond_us_china_tariffs'})
MERGE (e)-[r:TIGHTENS]->(n) SET r.severity = 0.4, r.sign = -1, r.why = 'Election outcome re-prices an expanded China-tariff / trade-war stance; seeds tariff CONSTRAINS targets (China exporters and China-supply-chain names) negative';

// =======================================================================
// ImpactRecord skeletons — ground-truth slots (filled by build_golden_dataset.py -> cypher/03).
// =======================================================================
UNWIND ['evt_tsmc_quake_2024', 'evt_nvda_ai_surge_2024', 'evt_chip_export_curbs_2024', 'evt_tesla_q1_miss_2024', 'evt_byd_overtakes_tesla_2024', 'evt_asml_guidance_cut_2024', 'evt_intel_q2_miss_2024', 'evt_micron_beat_2024', 'evt_google_antitrust_2024', 'evt_samsung_strike_2024', 'evt_apple_intelligence_wwdc_2024', 'evt_nvda_blackwell_delay_2024', 'evt_tsmc_earnings_beat_2024', 'evt_visa_doj_antitrust_2024', 'evt_fed_hawkish_dec_2024', 'evt_china_stimulus_2024', 'evt_yen_carry_unwind_2024', 'evt_deepseek_selloff_2025', 'evt_broadcom_ai_beat_2024', 'evt_smci_auditor_resign_2024', 'evt_skhynix_record_q3_2024', 'evt_marvell_ai_beat_2024', 'evt_apple_iphone16_demand_2024', 'evt_nvda_gtc_blackwell_2024', 'evt_taiwan_strait_scare_2022', 'evt_chip_controls_tighten_2023', 'evt_us_election_trump_2024'] AS eid
UNWIND ['MSFT', 'NVDA', 'TSMC', 'ASML', 'AMD', 'INTC', 'MU', 'AVGO', 'QCOM', 'ARM', 'TXN', 'MRVL', 'LRCX', 'AMAT', 'SMSN', 'SKH', 'ORCL', 'IBM', 'AMZN', 'GOOGL', 'META', 'NFLX', 'BABA', 'AAPL', 'DELL', 'SMCI', 'ANET', 'CSCO', 'FOXCONN', 'WDC', 'STX', 'TSLA', 'GM', 'BYD', 'CATL', 'PANA', 'V', 'MA', 'PYPL', 'JPM', 'GS', '4063.T', '3436.T', 'ENTG', 'LIN', 'AI.PA', '8035.T', 'KLAC', '6857.T', '6920.T', 'ASM.AS', 'SNPS', 'CDNS', 'SMIC', 'HUAHONG', 'TENCENT', 'BIDU', 'XIAOMI', 'JD', 'NAVER', 'KIOXIA', 'IFX.DE', 'STM', 'NXPI', 'SAP', 'SIE.DE', 'SU.PA', 'NOK', 'ERIC', 'VST', 'CEG', 'NRG', 'GEV', 'ETN', 'VRT', 'PWR', 'F', 'RIVN', 'TM', 'VOW3', 'NIO', 'LI', 'LGES', 'ALB', 'RXRX', 'SDGR', 'ILMN', 'TEM', 'SNDK', 'NANYA', 'HANMI', 'BESI', 'XOM', 'MP', 'FCX'] AS tk
MATCH (e:NewsEvent {id:eid}),(c:Company {ticker:tk})
MERGE (e)-[:HAS_RECORD]->(ir:ImpactRecord {id:'ir_'+eid+'_'+tk})
  ON CREATE SET ir.window='1d', ir.actualReturnPct=null, ir.abnormalReturnPct=null,
                ir.source='yfinance', ir.filled=false
MERGE (ir)-[:FOR_COMPANY]->(c);
