"""
gen_seed.py — regenerate cypher/01-marketmind-seed.cypher from data/*.json (+ data/macro.json).

Single source of truth = data/companies.json + data/edges.json + data/events.json + data/macro.json.
Edit those, run this, reload the seed. NEVER hand-edit the generated .cypher.

  python tools/gen_seed.py            # writes cypher/01-marketmind-seed.cypher
  python tools/gen_seed.py --check    # print summary, do not write

Emits (idempotent MERGE, safe to re-run on a live DB):
  • constraints (Company.ticker / NewsEvent.id / ImpactRecord.id / Country.code / Sector.name
                 / Commodity.id / Theme.id / Condition.id)
  • Company nodes (+ listedFrom + exposure scalars) ; Country (+region/bloc) ; Sector ; LOCATED_IN ; IN_SECTOR
  • cascade edges  SUPPLIES_TO|PARTNERS_WITH|OWNS|COMPETES_WITH   (the only types the engine walks)
  • macro layer (SEED-ONLY, never traversed): Commodity / Theme / Condition nodes
       + REVENUE_FROM / OPERATES_IN / EXPOSED_TO_POLICY / PRODUCES / CONSUMES / EXPOSED_TO_THEME / CONSTRAINS
  • NewsEvent (+scope/channelVector) -[:AFFECTS]-> Company  and macro seeds
       -[:HITS_COUNTRY|AFFECTS_COMMODITY|AFFECTS_THEME|ENACTS|TIGHTENS|LIFTS]-> macro node
  • ImpactRecord skeletons (one per event x tradable company) — filled by build_golden_dataset.py -> cypher/03
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
DATA = os.path.join(ROOT, "data")
OUT = os.path.join(ROOT, "cypher", "01-marketmind-seed.cypher")

COUNTRY_NAMES = {
    "US": "United States", "TW": "Taiwan", "KR": "South Korea", "JP": "Japan",
    "CN": "China", "HK": "Hong Kong", "NL": "Netherlands", "DE": "Germany",
    "FR": "France", "GB": "United Kingdom", "CH": "Switzerland", "CA": "Canada",
    "IE": "Ireland", "SE": "Sweden", "FI": "Finland", "IT": "Italy",
    "ES": "Spain", "IN": "India", "SG": "Singapore", "IL": "Israel",
}
TYPE_PROP = {"SUPPLIES_TO": "criticality", "PARTNERS_WITH": "strength", "OWNS": "pct", "COMPETES_WITH": "overlap"}
# Written onto Company nodes as CONTEXT only (Text2Cypher / human inspection). The cascade engine
# does NOT read these — Phase-0 exposure comes from the macro.json REVENUE_FROM/OPERATES_IN/... edges.
EXPO_SCALARS = ["chinaRev", "taiwanOps", "usRev", "euRev", "rateBeta", "fxBetaUSD", "policyBeta"]
# macro/exposure rel -> (target label, key prop). CONSTRAINS handled separately (Condition->Company).
REL_TARGET = {
    "REVENUE_FROM": ("Country", "code"), "OPERATES_IN": ("Country", "code"), "EXPOSED_TO_POLICY": ("Country", "code"),
    "PRODUCES": ("Commodity", "id"), "CONSUMES": ("Commodity", "id"), "EXPOSED_TO_THEME": ("Theme", "id"),
}
SEED_REL = {"country": "HITS_COUNTRY", "commodity": "AFFECTS_COMMODITY", "theme": "AFFECTS_THEME"}


def load(name, default=None):
    p = os.path.join(DATA, name)
    if not os.path.exists(p):
        return default
    with open(p, "r", encoding="utf-8") as f:
        return json.load(f)


def esc(s):
    return None if s is None else s.replace("\\", "\\\\").replace("'", "\\'")


def cy_str(s):
    return "null" if s is None else "'" + esc(s) + "'"


def cy_bool(b):
    return "true" if b else "false"


def cy_num(x):
    if isinstance(x, bool):
        return cy_bool(x)
    if isinstance(x, int):
        return str(x)
    f = float(x)
    return str(int(f)) if f.is_integer() else f"{f:g}"


def build():
    companies = load("companies.json")["companies"]
    edges = load("edges.json")["edges"]
    events = load("events.json")["events"]
    macro = load("macro.json", {}) or {}
    expo_edges = macro.get("exposureEdges", [])
    commodities = macro.get("commodities", [])
    themes = macro.get("themes", [])
    conditions = macro.get("conditions", [])
    macro_countries = {c["code"]: c for c in macro.get("countries", [])}

    tickers = {c["ticker"] for c in companies}
    tradable = [c["ticker"] for c in companies if c.get("tradable")]
    commodity_ids = {c["id"] for c in commodities}
    theme_ids = {t["id"] for t in themes}
    condition_ids = {c["id"] for c in conditions}

    # ---- defensive sanity (data_qa.py is the full gate) ----
    problems = []
    for e in edges:
        if e["from"] not in tickers or e["to"] not in tickers:
            problems.append(f"edge endpoint missing: {e['from']}-{e['type']}-{e['to']}")
        if e["type"] not in TYPE_PROP:
            problems.append(f"unknown edge type: {e['type']}")
    for ev in events:
        for h in ev.get("hits") or []:
            if h["ticker"] not in tickers:
                problems.append(f"event {ev['id']} hit missing {h['ticker']}")
    if problems:
        raise SystemExit("gen_seed: refusing to generate:\n  - " + "\n  - ".join(problems))

    L = []
    w = L.append

    w("// " + "=" * 71)
    w("// MARKETMIND — SEED  (GENERATED by tools/gen_seed.py — DO NOT HAND-EDIT)")
    w("// Source of truth: data/companies.json + edges.json + events.json + macro.json")
    w("// Idempotent (MERGE). Safe to re-run. Run in Neo4j Browser or cypher-shell.")
    w("//")
    w(f"// {len(companies)} companies · {len(edges)} cascade edges · {len(events)} events")
    w(f"// macro: {len(commodities)} commodities · {len(themes)} themes · {len(conditions)} conditions · {len(expo_edges)} exposure edges (SEED-ONLY)")
    w("//")
    w("// Cascade walks ONLY SUPPLIES_TO|PARTNERS_WITH|OWNS|COMPETES_WITH. Country/Sector/Commodity/")
    w("// Theme/Condition + exposure edges are SEED-ONLY context — never traversed company->company.")
    w("// " + "=" * 71)
    w("")

    # ---------- Constraints ----------
    w("// ---------- Constraints ----------")
    w("CREATE CONSTRAINT company_ticker IF NOT EXISTS FOR (c:Company)      REQUIRE c.ticker IS UNIQUE;")
    w("CREATE CONSTRAINT news_id        IF NOT EXISTS FOR (n:NewsEvent)    REQUIRE n.id     IS UNIQUE;")
    w("CREATE CONSTRAINT impact_id      IF NOT EXISTS FOR (i:ImpactRecord) REQUIRE i.id     IS UNIQUE;")
    w("CREATE CONSTRAINT country_code   IF NOT EXISTS FOR (k:Country)      REQUIRE k.code   IS UNIQUE;")
    w("CREATE CONSTRAINT sector_name    IF NOT EXISTS FOR (s:Sector)       REQUIRE s.name   IS UNIQUE;")
    if commodities:
        w("CREATE CONSTRAINT commodity_id   IF NOT EXISTS FOR (m:Commodity)    REQUIRE m.id     IS UNIQUE;")
    if themes:
        w("CREATE CONSTRAINT theme_id       IF NOT EXISTS FOR (h:Theme)        REQUIRE h.id     IS UNIQUE;")
    if conditions:
        w("CREATE CONSTRAINT condition_id   IF NOT EXISTS FOR (d:Condition)    REQUIRE d.id     IS UNIQUE;")
    w("")

    # ---------- Companies (+ listedFrom) ----------
    w("// ---------- Companies ----------")
    w("// tr = tradable, p = yfinance priceTicker (null = not directly tradable), bm = local benchmark, lf = first trade date, lat/lng = HQ coords (geo map)")
    w("UNWIND [")
    w(",\n".join(
        "  {{t:{t}, n:{n}, s:{s}, co:{co}, tr:{tr}, p:{p}, bm:{bm}, lf:{lf}, lat:{lat}, lng:{lng}}}".format(
            t=cy_str(c["ticker"]), n=cy_str(c["name"]), s=cy_str(c["sector"]), co=cy_str(c.get("country")),
            tr=cy_bool(c.get("tradable", False)), p=cy_str(c.get("priceTicker")), bm=cy_str(c.get("benchmark")),
            lf=cy_str(c.get("listedFrom")),
            lat=cy_num(c["lat"]) if c.get("lat") is not None else "null",
            lng=cy_num(c["lng"]) if c.get("lng") is not None else "null")
        for c in companies))
    w("] AS c")
    w("MERGE (x:Company {ticker:c.t})")
    w("  SET x.name = c.n, x.sector = c.s, x.country = c.co,")
    w("      x.tradable = c.tr, x.priceTicker = c.p, x.benchmark = c.bm, x.listedFrom = c.lf,")
    w("      x.lat = c.lat, x.lng = c.lng;")
    w("")

    # ---------- Exposure scalars (only the macro-anchor names that have them) ----------
    exp_rows = [c for c in companies if c.get("exposure")]
    if exp_rows:
        w("// ---------- Exposure scalars (macro-anchor companies) ----------")
        w("UNWIND [")
        w(",\n".join(
            "  {{t:{t}, {kv}}}".format(
                t=cy_str(c["ticker"]),
                kv=", ".join(f"{k}:{cy_num(c['exposure'][k])}" for k in EXPO_SCALARS if k in c["exposure"]))
            for c in exp_rows))
        w("] AS e")
        w("MATCH (x:Company {ticker:e.t})")
        # plain SET per scalar (a key absent from the row map reads as null in Cypher)
        w("  SET " + ", ".join(f"x.{k} = e.{k}" for k in EXPO_SCALARS) + ";")
        w("")

    # ---------- Countries (+region/bloc) + LOCATED_IN ----------
    codes = sorted({c.get("country") for c in companies if c.get("country")})
    if codes:
        w("// ---------- Countries (context) + LOCATED_IN ----------")
        w("UNWIND [")
        w(",\n".join(
            "  {{code:{c}, name:{n}, region:{r}, bloc:{b}}}".format(
                c=cy_str(code), n=cy_str(macro_countries.get(code, {}).get("name") or COUNTRY_NAMES.get(code, code)),
                r=cy_str(macro_countries.get(code, {}).get("region")), b=cy_str(macro_countries.get(code, {}).get("bloc")))
            for code in codes))
        w("] AS k")
        w("MERGE (x:Country {code:k.code}) SET x.name = k.name, x.region = k.region, x.bloc = k.bloc;")
        w("")
        w("UNWIND [")
        w(",\n".join("  {{t:{t}, c:{c}}}".format(t=cy_str(c["ticker"]), c=cy_str(c["country"]))
                     for c in companies if c.get("country")))
        w("] AS m")
        w("MATCH (c:Company {ticker:m.t}),(k:Country {code:m.c})")
        w("MERGE (c)-[:LOCATED_IN]->(k);")
        w("")

    # ---------- Sectors + IN_SECTOR (context only) ----------
    sectors = sorted({c.get("sector") for c in companies if c.get("sector")})
    if sectors:
        w("// ---------- Sectors (context, NOT traversed) + IN_SECTOR ----------")
        w("UNWIND [" + ", ".join(cy_str(s) for s in sectors) + "] AS sname")
        w("MERGE (s:Sector {name:sname});")
        w("")
        w("UNWIND [")
        w(",\n".join("  {{t:{t}, s:{s}}}".format(t=cy_str(c["ticker"]), s=cy_str(c["sector"]))
                     for c in companies if c.get("sector")))
        w("] AS m")
        w("MATCH (c:Company {ticker:m.t}),(s:Sector {name:m.s})")
        w("MERGE (c)-[:IN_SECTOR]->(s);")
        w("")

    # ---------- Cascade edges ----------
    by_type = {t: [] for t in TYPE_PROP}
    for e in edges:
        by_type[e["type"]].append(e)
    for rtype, label, prop in [("SUPPLIES_TO", "supplier -> customer", "criticality"),
                               ("PARTNERS_WITH", "partnership", "strength"),
                               ("OWNS", "parent -> subsidiary (pct)", "pct"),
                               ("COMPETES_WITH", "rivalry (sign-flipping channel)", "overlap")]:
        items = by_type[rtype]
        if not items:
            continue
        w(f"// ---------- {rtype} {{{prop}}}  ({label}) ----------")
        w("UNWIND [")
        w(",\n".join("  {{a:{a}, b:{b}, w:{w}}}".format(a=cy_str(e["from"]), b=cy_str(e["to"]), w=cy_num(e["weight"]))
                     for e in items))
        w("] AS e")
        w("MATCH (s:Company {ticker:e.a}),(d:Company {ticker:e.b})")
        w(f"MERGE (s)-[r:{rtype}]->(d) SET r.{prop} = e.w;")
        w("")

    # ---------- Macro nodes (SEED-ONLY) ----------
    if commodities:
        w("// ---------- Commodity nodes (seed-only) ----------")
        w("UNWIND [")
        w(",\n".join("  {{id:{i}, name:{n}, category:{c}, geo:{g}}}".format(
            i=cy_str(m["id"]), n=cy_str(m.get("name")), c=cy_str(m.get("category")), g=cy_str(m.get("geoConcentration")))
            for m in commodities))
        w("] AS m")
        w("MERGE (x:Commodity {id:m.id}) SET x.name = m.name, x.category = m.category, x.geoConcentration = m.geo;")
        w("")
    if themes:
        w("// ---------- Theme nodes (seed-only) ----------")
        w("UNWIND [")
        w(",\n".join("  {{id:{i}, name:{n}, kind:{k}, desc:{d}}}".format(
            i=cy_str(t["id"]), n=cy_str(t.get("name")), k=cy_str(t.get("kind")), d=cy_str(t.get("description")))
            for t in themes))
        w("] AS t")
        w("MERGE (x:Theme {id:t.id}) SET x.name = t.name, x.kind = t.kind, x.description = t.desc;")
        w("")
    if conditions:
        w("// ---------- Condition nodes (standing state — seed-only) ----------")
        w("UNWIND [")
        w(",\n".join("  {{id:{i}, kind:{k}, status:{st}, sd:{sd}, ed:{ed}, jur:{j}, dom:{dm}, sev:{sv}, desc:{ds}}}".format(
            i=cy_str(c["id"]), k=cy_str(c.get("kind")), st=cy_str(c.get("status")), sd=cy_str(c.get("startDate")),
            ed=cy_str(c.get("endDate")), j=cy_str(c.get("jurisdiction")), dm=cy_str(c.get("domain")),
            sv=cy_num(c.get("severity", 0)), ds=cy_str(c.get("description")))
            for c in conditions))
        w("] AS d")
        w("MERGE (x:Condition {id:d.id})")
        w("  SET x.kind=d.kind, x.status=d.status, x.startDate=d.sd, x.endDate=d.ed,")
        w("      x.jurisdiction=d.jur, x.domain=d.dom, x.severity=d.sev, x.description=d.desc;")
        w("")

    # ---------- Exposure edges (SEED-ONLY) ----------
    by_rel = {}
    for e in expo_edges:
        by_rel.setdefault(e["rel"], []).append(e)
    for rel, items in by_rel.items():
        w(f"// ---------- {rel} (seed-only exposure) ----------")
        w("UNWIND [")
        w(",\n".join("  {{a:{a}, b:{b}, v:{v}, sg:{sg}, ch:{ch}, src:{src}}}".format(
            a=cy_str(e["from"]), b=cy_str(e["to"]), v=cy_num(e.get("value", 0)),
            sg=cy_num(e.get("sign", 1)), ch=cy_str(e.get("channel")), src=cy_str(e.get("source")))
            for e in items))
        w("] AS e")
        if rel == "CONSTRAINS":
            w("MATCH (cond:Condition {id:e.a}),(c:Company {ticker:e.b})")
            w("MERGE (cond)-[r:CONSTRAINS]->(c) SET r.value=e.v, r.sign=e.sg, r.channel=e.ch, r.source=e.src;")
        else:
            lbl, key = REL_TARGET[rel]
            w(f"MATCH (c:Company {{ticker:e.a}}),(n:{lbl} {{{key}:e.b}})")
            w(f"MERGE (c)-[r:{rel}]->(n) SET r.value=e.v, r.sign=e.sg, r.channel=e.ch, r.source=e.src;")
        w("")

    # ---------- News events + AFFECTS + macro seeds ----------
    w("// " + "=" * 71)
    w("// NEWS EVENTS  (AFFECTS company hits; macro seeds -> country/commodity/theme/condition)")
    w("// " + "=" * 71)
    w("")
    for ev in events:
        hits = ev.get("hits") or []
        seeds = ev.get("seeds") or []
        mags = [h["sign"] * h["severity"] for h in hits] + [s["sign"] * s["severity"] for s in seeds]
        sentiment = round(sum(mags) / len(mags), 2) if mags else 0.0
        cv = ev.get("channelVector") or {}
        w(f"// {ev['id']}  ({ev['date']}, {ev.get('category')}, scope={ev.get('scope', 'company')})")
        w(f"MERGE (e:NewsEvent {{id:{cy_str(ev['id'])}}})")
        w(f"  SET e.headline = {cy_str(ev['headline'])},")
        w(f"      e.source = {cy_str(ev.get('source'))}, e.url = {cy_str(ev.get('url'))},")
        w(f"      e.sentiment = {cy_num(sentiment)}, e.category = {cy_str(ev['category'])}, e.scope = {cy_str(ev.get('scope', 'company'))},")
        if cv:
            w("      " + ", ".join(f"e.cv_{k} = {cy_num(v)}" for k, v in cv.items()) + ",")
        w(f"      e.date = {cy_str(ev['date'])}, e.ts = datetime('{ev['date']}T00:00:00Z');")
        if hits:
            w("WITH 1 AS _")
            w("UNWIND [")
            w(",\n".join("  {{t:{t}, d:{d}, sg:{sg}, why:{why}}}".format(
                t=cy_str(h["ticker"]), d=cy_num(h["severity"]), sg=cy_num(h["sign"]), why=cy_str(h.get("why")))
                for h in hits))
            w("] AS h")
            w(f"MATCH (e:NewsEvent {{id:{cy_str(ev['id'])}}}),(c:Company {{ticker:h.t}})")
            w("MERGE (e)-[a:AFFECTS]->(c) SET a.directImpact = h.d, a.sign = h.sg, a.why = h.why;")
        for s in seeds:
            typ = s["type"]
            if typ == "condition":
                rel = (s.get("conditionAction") or "ENACTS").upper()
                lbl, key = "Condition", "id"
            else:
                rel = SEED_REL.get(typ)
                lbl, key = ("Country", "code") if typ == "country" else (
                    "Commodity", "id") if typ == "commodity" else ("Theme", "id")
            if not rel:
                continue
            w("WITH 1 AS _")
            w(f"MATCH (e:NewsEvent {{id:{cy_str(ev['id'])}}}),(n:{lbl} {{{key}:{cy_str(s['id'])}}})")
            w(f"MERGE (e)-[r:{rel}]->(n) SET r.severity = {cy_num(s['severity'])}, r.sign = {cy_num(s['sign'])}, r.why = {cy_str(s.get('why'))};")
        w("")

    # ---------- ImpactRecord skeletons ----------
    w("// " + "=" * 71)
    w("// ImpactRecord skeletons — ground-truth slots (filled by build_golden_dataset.py -> cypher/03).")
    w("// " + "=" * 71)
    w("UNWIND [" + ", ".join(cy_str(ev["id"]) for ev in events) + "] AS eid")
    w("UNWIND [" + ", ".join(cy_str(tk) for tk in tradable) + "] AS tk")
    w("MATCH (e:NewsEvent {id:eid}),(c:Company {ticker:tk})")
    w("MERGE (e)-[:HAS_RECORD]->(ir:ImpactRecord {id:'ir_'+eid+'_'+tk})")
    w("  ON CREATE SET ir.window='1d', ir.actualReturnPct=null, ir.abnormalReturnPct=null,")
    w("                ir.source='yfinance', ir.filled=false")
    w("MERGE (ir)-[:FOR_COMPANY]->(c);")
    w("")

    stats = {"companies": len(companies), "tradable": len(tradable), "edges": len(edges), "events": len(events),
             "commodities": len(commodities), "themes": len(themes), "conditions": len(conditions), "expo": len(expo_edges)}
    return "\n".join(L), stats


def main():
    text, stats = build()
    print("  ".join(f"{k}={v}" for k, v in stats.items()))
    if "--check" in sys.argv:
        print("--check: not writing.")
        return
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    print(f"wrote {os.path.relpath(OUT, ROOT)}  ({text.count(chr(10))+1} lines)")


if __name__ == "__main__":
    main()
